### ISSUE TITLE
Setting volume

### ISSUE THREAD

**Issue by henrikekblad** [Supergiovane/node-red-contrib-sonospollytts#1]
Would it be possible to have a volume parameter in in incoming message to allow volume control dynamically?

I use this plugin both for tts-announcements and sending in url an mp3-url (for our doorbell). Would have been great to be able to tune the volume individually for different inputs. 

Thanks!

**Comment by henrikekblad** [comment]
... and before doing tts/mp3 announcements it should save the old volume and restore it afterwards (and perhaps resume any music/queue playing).

**Comment by Supergiovane** [comment]
Hello henrikekblad
Can you confirm that this whould be OK for you?
1) Specify the volume while sending the text to be spoken out (for example msg.volume=50). This should cover all your needs.
2) Resume playback of music with reverted volume (the previous volume).
Thanks.

**Comment by henrikekblad** [comment]
Yes, exactly what I mean.

Thanks
Henrik

**Comment by Supergiovane** [comment]
Partially worked on your issue.
Added msg.volume to set the volume.

**Comment by henrikekblad** [comment]
Ok! Will do some tests when I'm back home in a couple of days.

**Comment by rephlex00** [comment]
This works for me.

**Comment by Supergiovane** [comment]
Closed
