### ISSUE TITLE
Play to all zones 

### ISSUE THREAD

**Issue by nodecentral** [Supergiovane/node-red-contrib-sonospollytts#10]
Hi,

Not sure if I am missing something, but how do I get it to play the TTS across all zones,  is it just to the Sonos IP I set up?

**Comment by Supergiovane** [comment]
Hello
You need to group the players using sonos app.

**Comment by nodecentral** [comment]
Hi @Supergiovane 

Just wondering if there has been any further thought / development on this achieving such a play to all zones feature ?

**Comment by nodecentral** [comment]
I’ve been using this other github (https://github.com/jishi/node-sonos-http-api ) approach to get it to ‘play to all’ - just curious if you’ll have the functionality too soon.

**Comment by Supergiovane** [comment]
Hello
Thank you for using my node. 
Playing on all zone can be achieved by grouping your sonos devices. 
Do you have any suggestion on how do you want this to differently work?

**Comment by nodecentral** [comment]
What would be cool, would be a ‘Discover Sonos Devices’ option, where it would go out and find all the zone players on your network (or you could add them all manually) and then provide the ability to select one or more devices to play the TTS through

**Comment by Supergiovane** [comment]
Hi NodeCentral
because i haven't more than one device (i've only a Sonos AMP and a Sub), as soon as something is ready, are you able to test it for me?

**Comment by danzeisen** [comment]
I it helps, I could test as well. I have a few Player 1, 3, 5, Bar, SUB.

**Comment by nodecentral** [comment]
> Hi NodeCentral
> because i haven't more than one device (i've only a Sonos AMP and a Sub), as soon as something is ready, are you able to test it for me?

Sure, more than happy to help 👍

**Comment by Supergiovane** [comment]
Hello all,
ok, that's doable.
I hope to release a new 1.1.16 version in the weekend, coronavirus permitting.
Thank you for your patience.

**Comment by Supergiovane** [comment]
V 1.1.16 is out. You should see it in some minutes.
Please report any problem you have.

**Comment by nodecentral** [comment]
Hi, I have updated the app to the latest version v 1.1.23 - (rebooted) and then added a couple of other zones in but sadly  it doesn’t work ?

 I can see an Error transport message pop up under the node - Any ideas ?

**Comment by nodecentral** [comment]
Hi, it looks like the problem is with the TTS cache, I had this set to ‘leave the TTS cache untouched...’ if I put it to the default it works again.  

I’m using this NR in a Docker container - where is it expecting the cache to be stored ?

**Comment by Supergiovane** [comment]
Hi NodeCentral.
Have you tried to change the option from "leave" to the default again and restart node-red?
The cache is created independently from this option and it is used independently. 
The only difference, is that at restart, if you select the default to "delete" the cache, it delete the cache, otherwise not.
Let me check if i made some syntax error...

**Comment by Supergiovane** [comment]
No, no syntax errors.
Are you able to re-set the option to "leave" and post here the debug log of node-red?

**Comment by Supergiovane** [comment]
> If it helps, I could test as well. I have a few Player 1, 3, 5, Bar, SUB.

Hello Dan
Do you have the same Problem as NodeCentral?
