### ISSUE TITLE
Node-Red stops starting after latest update

### ISSUE THREAD

**Issue by tsprivate** [Supergiovane/node-red-contrib-sonospollytts#11]
Hi,

I was using your node for a while without issues. I was just updating to your latest node and Node-Red was crashing with sonospollytts failure message at the start-up. There was no other change to the flow!

1) How can I install a previous version of your node
2) what do you need to investigate the current crash ?
![image](https://user-images.githubusercontent.com/41630517/57206728-7a47fc80-700b-11e9-82ee-f069576cc32e.png)

regards

**Comment by Supergiovane** [comment]
Hello,
i'm trying to reproduce the issue.
What do you see in the startup failure message?


Il giorno 6 mag 2019, alle ore 06:03, tsprivate <notifications@github.com> ha scritto:

Hi,

I was using your node for a while without issues. I was just updating to your latest node and Node-Red was crashing with sonospollytts failure message at the start-up. There was no other change to the flow!

How can I install a previous version of your node
what do you need to investigate the current crash ?
regards

**Comment by Supergiovane** [comment]
I'll investigate your issue.
Have no other users reporting that.
I'll revert to you ASAP

**Comment by Supergiovane** [comment]
By reading yourlog, it seems that this causes the problem:
node.SonosClient.getCurrentState()**.then**(state=>{...
It seems that she SonosClient isn't correctly assigned.
No changes where made in that part of the code since the beginning.

Can you please post here the output of the command:
**npm show sonos version**

Thanks.

**Comment by tsprivate** [comment]
Hi,
thank you for the quick response. As said I was using an earlier version ( I thiink 2+ months) old and it was working fine and I just updated  your node

1) the result of "npm show sonos version" is 1.10.1
2) I have re-installed as you advised and the update was successful. The node is working as before

Thanks for the great help!

**Comment by Supergiovane** [comment]
The sonos node 1.10.1 is up to date.
Good to hear that now it works. Maybe something was missing.
Bye!
