### ISSUE TITLE
request:  Node-Out with status

### ISSUE THREAD

**Issue by tsprivate** [Supergiovane/node-red-contrib-sonospollytts#13]
Is it possible to get an Node-Out which is providing status updates like
  
1) completed: true/false       ==> no more TTS in queue)
2) queued:     5                    ==> 5 TTS are in queue
3) error:         "Error Msg"    ==> Shows error message

with this feature it would be able to suspend any audio currently playing on the Sonos system and to resume after the TTS has completed!  Therefore 1) would be the most welcome.

Additionally: There is a nice SONOS npm (https://github.com/bencevans/node-sonos) .. would it be possible to merge some features. That would be really good to control the SONOS.

Thanks for considering

**Comment by Supergiovane** [comment]
Hello
Will take a look at all and i’ll revert to you. 


Sent by Massimo on the move

Il giorno 7 mag 2019, alle ore 04:27, tsprivate <notifications@github.com> ha scritto:

Is it possible to get an Node-Out which is providing status updates like

completed: true/false ==> no more TTS in queue)
queued: 5 ==> 5 TTS are in queue
error: "Error Msg" ==> Shows error message
with this feature it would be able to suspend any audio currently playing on the Sonos system and to resume after the TTS has completed! Therefore 1) would be the most welcome.

Additionally: There is a nice SONOS npm (https://github.com/bencevans/node-sonos) .. would it be possible to merge some features. That would be really good to control the SONOS.

Thanks for considering

**Comment by Supergiovane** [comment]
Hello tsprivate
the .completed output message is implemented in Version 1.0.14
The feature is under testing und will be released today.
