### ISSUE TITLE
https with node-red-contrib-sonospollytts

### ISSUE THREAD

**Issue by igordewinter** [Supergiovane/node-red-contrib-sonospollytts#15]
Hello 

I'm new to node-red-contrib-sonospollytts. I tested node-red-contrib-sonospollytts with node-red configured on https on a pi. Than node-red-contrib-sonospollytts doesn't work. It can't open  http://<<IP PI>>:<<port>>/tts/tts,mp3.  When I switch my node-red implementation to HTTP everthing work fine. And I found that sonos only play mp3 file form a  https source with a valid certificated.

What am I doning wrong?

**Comment by Supergiovane** [comment]
Hello
From an https connection, you cannot open an http connection. 
You need to use http instead of https, because using https certificates isn’t implemented yet in sonospollytts.

**Comment by igordewinter** [comment]
Hello 

Thanks, for the very quick response! Looks http is the way to go ;-)

Niels
