### ISSUE TITLE
Credential type 'sonospollytts-config' is not registered

### ISSUE THREAD

**Issue by pi200** [Supergiovane/node-red-contrib-sonospollytts#18]
Hello,
when I try to set up the node and click deploy I get the following error messages:

**Flows stopped due to missing node types.

sonospollytts-config
sonospollytts**

In the log I can see the following:
**1 Sep 14:08:07 - [info] Installing module: node-red-contrib-sonospollytts, version: 1.0.18
1 Sep 14:08:14 - [info] Installed module: node-red-contrib-sonospollytts
1 Sep 14:08:14 - [info] Added node types:
1 Sep 14:08:14 - [info]  - node-red-contrib-sonospollytts:sonospollytts-config : SyntaxError: Unexpected token function (line:11)
1 Sep 14:08:14 - [info]  - node-red-contrib-sonospollytts:sonospollytts : SyntaxError: Unexpected token function (line:11)
1 Sep 14:09:46 - [warn] Credential type 'sonospollytts-config' is not registered
1 Sep 14:09:46 - [info] Stopping flows
1 Sep 14:09:46 - [info] Stopped flows
1 Sep 14:09:46 - [info] Waiting for missing types to be registered:
1 Sep 14:09:46 - [info]  - sonospollytts-config
1 Sep 14:09:46 - [info]  - sonospollytts**

I have also filled in all data in the form. But I haven't managed to get it to running yet.

**Comment by Supergiovane** [comment]
Hello pi200
It’s the first time you install the node?

**Comment by pi200** [comment]
Yes so i´ve tried it several times, deinstalling and installing again. 
I never got it to work.

**Comment by Supergiovane** [comment]
I’ll check inmediately and i’ll let you know!!

**Comment by pi200** [comment]
Just for your information, I don´t know if it is relevant but I´m running node-red on Docker.

Thanks for your help!

**Comment by Supergiovane** [comment]
Hmmm.... Can you try to uninstall sonospollytts and install an older version?
To install an older version:
cd .node-red
npm i node-red-contrib-sonospollytts@1.0.16
Then let me know.

Thanks.

**Comment by Supergiovane** [comment]
Can you tell me your node version?
The command to show node version is: node -v

**Comment by pi200** [comment]
Hi I tried to install a older version of the module, but when I install it manually via npm I can´t even find the node in the pallet. When I Try to enable it:

**1 Sep 16:51:02 - [warn] Failed to enable node:
1 Sep 16:51:02 - [warn]  - sonospollytts : SyntaxError: Unexpected token function (line:14)
1 Sep 16:51:04 - [warn] Failed to enable node:
1 Sep 16:51:04 - [warn]  - sonospollytts : SyntaxError: Unexpected token function (line:14)**

Node Version is:
**v6.14.1**

**Comment by Supergiovane** [comment]
Eh... the node is very old. 
The minimum node version that accepts “promises” is 7.9
Sonospollytts is designed to use at least 8.9.0 onwards
Please update node.js to the latest and you’ll enjoy the node!

If you’re on debian : apt install nodejs

**Comment by pi200** [comment]
Oh, this is embarrassing.
I didn't check the most obvious one.

My Node Red version was also outdated.
Now everything runs as it should!

Thanks for your help and for the great Node

**Comment by Supergiovane** [comment]
Non problem. 👍🏻
