### ISSUE TITLE
Unable to play - the connection to 192.168.x.xxx was lost

### ISSUE THREAD

**Issue by MTxx87** [Supergiovane/node-red-contrib-sonospollytts#19]
I am running node red on raspberry pi 3 and I am getting this error in Sonos app when I try to run the simple Hello World flow that you provided.

**Unable to play - 'tts.mp3?f=/tmp/hailing.mp3' the connection to 192.168.1.xxx:1880 was lost**

Node red log is the following

> 28 Sep 17:01:53 - [info] Moving hailing file hailing.mp3 to temp dir /tmp
28 Sep 17:01:53 - [info] Started modified nodes
28 Sep 17:01:59 - [info] SonosPollyTTS: Leggi .MP3 diretto e skip polly, filename: hailing.mp3
28 Sep 17:01:59 - [info] SonosPollyTTS: DEBUG - fromcache : /tmp/Ciao Mondo_em_ Come stai_qm__Joanna.mp3
28 Sep 17:02:13 - [info] SonosPollyTTS: Leggi .MP3 diretto e skip polly, filename: hailing.mp3
28 Sep 17:02:14 - [info] SonosPollyTTS: DEBUG - fromcache : /tmp/Ciao Mondo_em_ Come stai_qm__Joanna.mp3
28 Sep 17:02:26 - [info] SonosPollyTTS: Leggi .MP3 diretto e skip polly, filename: hailing.mp3
28 Sep 17:02:26 - [info] SonosPollyTTS: DEBUG - fromcache : /tmp/Ciao Mondo_em_ Come stai_qm__Joanna.mp3
28 Sep 17:21:12 - [info] SonosPollyTTS: Leggi .MP3 diretto e skip polly, filename: hailing.mp3
28 Sep 17:21:13 - [info] SonosPollyTTS: DEBUG - fromcache : /tmp/Ciao Mondo_em_ Come stai_qm__Joanna.mp3
28 Sep 17:21:35 - [info] SonosPollyTTS: Leggi .MP3 diretto e skip polly, filename: hailing.mp3
28 Sep 17:21:36 - [info] SonosPollyTTS: DEBUG - fromcache : /tmp/Ciao Mondo_em_ Come stai_qm__Joanna.mp3
28 Sep 17:25:44 - [info] SonosPollyTTS: Leggi .MP3 diretto e skip polly, filename: hailing.mp3
28 Sep 17:25:46 - [info] SonosPollyTTS: HandleQueue - Polly is downloading the file, exit

I have checked the folder /tmp and file hailing.mp3 and temporarily changed their permission to 777 to check if was a permission problem, but with no better result.
Any input on this problem?

Thanks.

**Comment by Supergiovane** [comment]
Hello
You need to fill the options with your own IP and amazon aws credentials
Can you please post here a screenshot of the config node?
Thanks

**Comment by MTxx87** [comment]
It doesn't seem to be a problem with AWS.
I think the request goes through correctly since the audio file 

gets saved in the /temp folder:

> Benvenuti_pause_Wilkommen_pause_Wellcome_em__Joanna.mp3
Ciao Mondo_em_ Come stai_qm__Giorgio.mp3
Ciao Mondo_em_ Come stai_qm__Joanna.mp3

Here below the screenshots.

<img width="487" alt="Screenshot 2019-09-28 at 19 38 08" src="https://user-images.githubusercontent.com/12138301/65820323-b59bcf80-e227-11e9-9d0d-f6b6c9fd5ad4.png">
<img width="495" alt="Screenshot 2019-09-28 at 19 37 43" src="https://user-images.githubusercontent.com/12138301/65820324-b59bcf80-e227-11e9-9dba-02b001f1315a.png">

**Comment by Supergiovane** [comment]
Do uou run node-red alone or behind a homeassistant, for example?
From the log, the node works ok until it tells sonos to connect to your node-red. 
Is the sonos IP x fixed IP, as well as Raspberry IP?

**Comment by MTxx87** [comment]
Node red runs alone on the raspberry.
The Sonos gets an automatic IP from my router.
The raspberry PI instead I have set the router to assign always the same IP (I need the same IP for various reasons), so it is "fixed" in that sense.

**Comment by Supergiovane** [comment]
The sonos should have a fixed ip as well. Uou can use the dhcp reservation. 
You should not have any issue if both IP are reachable. Have you tried to reoot the pi after installing sonospollytts?
Please paste the complete nodered log, i’ll check it tomorrow

**Comment by MTxx87** [comment]
I have done a reboot of the PI and assigned the fixed IP to the SONOS, but without luck.
The error I get in the app looks the same.
This is the complete log I get when running "node-red-log".

> 29 Sep 12:07:38 - [info] Server now running at https://127.0.0.1:1880/
29 Sep 12:07:38 - [warn]
Your flow credentials file is encrypted using a system-generated key.
If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.
You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
29 Sep 12:07:38 - [info] Starting flows
Connecting to Flic Daemon at 127.0.0.1:5551
29 Sep 12:07:39 - [info] SonosPollyTTS: ConfigNode:[object Object]
29 Sep 12:07:39 - [info] SonosPollyTTS: ConfigNode:[object Object]
29 Sep 12:07:40 - [info] SonosPollyTTS: Temp dir set to /tmp
29 Sep 12:07:40 - [info] SonosPollyTTS: Node-Red URL: http://192.168.1.219:1880
29 Sep 12:07:40 - [info] Moving hailing file hailing.mp3 to temp dir /tmp
29 Sep 12:07:40 - [info] Started flows
29 Sep 12:09:50 - [info] SonosPollyTTS: Leggi .MP3 diretto e skip polly, filename: hailing.mp3
29 Sep 12:09:52 - [info] SonosPollyTTS: HandleQueue - Polly is downloading the file, exit
29 Sep 12:10:00 - [info] SonosPollyTTS: Leggi .MP3 diretto e skip polly, filename: hailing.mp3
29 Sep 12:10:01 - [info] SonosPollyTTS: HandleQueue - Polly is downloading the file, exit
29 Sep 12:10:26 - [info] SonosPollyTTS: Leggi .MP3 diretto e skip polly, filename: hailing.mp3
29 Sep 12:10:27 - [info] SonosPollyTTS: DEBUG - fromcache : /tmp/Ciao Mondo_em_ Come stai_qm__Joanna.mp3

**Comment by Supergiovane** [comment]
Hello
Can you try disabling https?

**Comment by MTxx87** [comment]
I have disabled HTTPS and now it works fine, thanks for your help!
Could it work with https in the future?

**Comment by Supergiovane** [comment]
Good! I must see if sonos implements the https protocol in the url stream api, because it depends on that.
