### ISSUE TITLE
Great lib, could be improved.

### ISSUE THREAD

**Issue by svrooij** [Supergiovane/node-red-contrib-sonospollytts#2]
I like the way you implemented the Polly part, kudos!!

But the way you send it to Sonos could be greatly improved. I implemented a [playNotification](https://github.com/bencevans/node-sonos/blob/master/docs/sonos.md#sonossonosplaynotificationoptions) method.

This suits your needs greatly. It only returns when it finishes playing the url. So you can use it to Play multiple tts urls. Will automatically revert to the last playing song (and volume)

**Comment by Supergiovane** [comment]
Thank you for the suggestion
Already tested playNotification but in some circumstances, it doesn't work as expected.
Will keep an eye on that in the future.
