### ISSUE TITLE
Sonos mentions: "tts.mp3F=/data/public/2.mp3" is not availabe

### ISSUE THREAD

**Issue by JorinL** [Supergiovane/node-red-contrib-sonospollytts#21]
Sonos mentions: "tts.mp3F=/data/public/2.mp3" is not availabe

Which is completely correct. Only "/data/public/2.mp3" is available for playback ;-)
What means from Sonos side: http://duffstation:1880/2.mp3
Seems like a var comes into the output to sonos?

![grafik](https://user-images.githubusercontent.com/33031729/67485212-e1b14180-f669-11e9-87bc-f69705d9ce2f.png)

Sonos Controller:
![grafik](https://user-images.githubusercontent.com/33031729/67485264-f68dd500-f669-11e9-9024-d675ab3f9467.png)

**Comment by Supergiovane** [comment]
Hello JorinL,
do you still have this problem?
Have you tried to leave the default temp field blank?

**Comment by JorinL** [comment]
Yep - problem persists.

Empty uses /tmp - same problem.

It needs to be a directory which is available for other machines/sonos on my node-red server right?

For me that would be from node red perspective /data/public/
from LAN via http "http://duffstation:1880/some_mp3_file.mp3

Just for the info my Node Red is inside a docker container - but available for the local network.

**Comment by Supergiovane** [comment]
Hello
Once created, the node tells Sonos to contact an endpoint it created in your node-red. Sonos contacts this endpoint. The endpoint read the mp3 from your temp folder and starts streaming it to sonos. Sonos is not in direct "contact" with your directory.
I saw you're in Germany. Do you maybe run Node-Red behind homematic?

**Comment by JorinL** [comment]
Hi,
no the Node-Red ist an instance alone on a Rancher Kubernetes Cluster with Docker under the hood.
It is mainly connected over MQTT to a "FHEM" instance. 

Maybe this "endpoint" has no access to the directory? This is spawning on the node JS where Node-Red is running (same user?)?

**Comment by Supergiovane** [comment]
Hi,
Has Docker the port forwarting to node-red? If not, Sonos cannot contact node-red.
Node-red must have r/w access rights to the temp folder, but it has, otherwise you'll not hear the hailing.

**Comment by JorinL** [comment]
Jep - port forwarding 1880 ist done - is there more needed for this node?
r/w is given.

I redeployed the container / like a reboot :-D

**Comment by JorinL** [comment]
Mp3s are working fine.


Log:

The` mp3 files are working fine. I did test that.

node-red-docker@1.0.1 start /usr/src/node-red

node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"

24 Oct 13:49:19 - [info]

Welcome to Node-RED

===================

24 Oct 13:49:19 - [info] Node-RED version: v1.0.1

24 Oct 13:49:19 - [info] Node.js  version: v12.10.0

24 Oct 13:49:19 - [info] Linux 4.15.0-66-generic x64 LE

24 Oct 13:49:20 - [info] Loading palette nodes

24 Oct 13:49:21 - [info] Dashboard version 2.17.1 started at /ui

24 Oct 13:49:21 - [info] Settings file  : /data/settings.js

24 Oct 13:49:21 - [info] HTTP Static    : /data/public

24 Oct 13:49:21 - [info] Context store  : 'default' [module=memory]

24 Oct 13:49:21 - [info] User directory : /data

24 Oct 13:49:21 - [warn] Projects disabled : editorTheme.projects.enabled=false

24 Oct 13:49:21 - [info] Flows file     : /data/flows.json

24 Oct 13:49:21 - [info] Starting flows

24 Oct 13:49:21 - [info] SonosPollyTTS: ConfigNode:[object Object]

24 Oct 13:49:21 - [info] SonosPollyTTS: Temp dir set to /tmp

24 Oct 13:49:21 - [info] SonosPollyTTS: Node-Red URL: http://192.168.0.8:1880

24 Oct 13:49:21 - [info] Moving hailing file hailing.mp3 to temp dir /tmp

24 Oct 13:49:22 - [info] Started flows

24 Oct 13:49:22 - [info] Server now running at http://127.0.0.1:1880/admin/

24 Oct 13:49:22 - [info] [mqtt-broker:707c62cd.b68904] Connected to broker: mqtt://192.168.0.8:1883


Checking for Hue Bridge updates…


SoftwareUpdate {

  attributes: Attributes { attributes: { checkforupdate: true }, changed: {} }

}

Updating Hue Bridge Firmware and Lights…

24 Oct 13:49:55 - [info] SonosPollyTTS: Leggi .MP3 diretto e skip polly, filename: hailing.mp3

24 Oct 13:49:56 - [info] SonosPollyTTS: HandleQueue - Polly is downloading the file, exit

**Comment by Supergiovane** [comment]
Ok let me finish an update to the knx-ultimate node, then i'll look at this! I know that when running behind something, like docker, homeassistant and so on, Sonos has issues to contact node-red to start streaming. I'll look again into that.
Is there nothing below "24 Oct 13:49:56 - [info] SonosPollyTTS: HandleQueue - Polly is downloading the file, exit" line?

**Comment by JorinL** [comment]
No sorry - that is the last line appearing.

Is this /tts/tts.mp3 expected somewhere in the filesystem or viewable on https://192.168.0.8:1880/tts/tts.mp3 ? Or is it really not an existent file? :-D

**Comment by Supergiovane** [comment]
"/tts/tts.mp3" it's an non existent file. "tts" is the endpoint that sonos calls and the tts.mp3 is a fake file.
I suspect there's something that stops sonos to reach the endpoint. I need to dive in the code.

**Comment by JorinL** [comment]
What works ist to play a mp3 which i used with node red and a direct connected speaker:

24 Oct 14:20:44 - [info] SonosPollyTTS: Leggi HTTP filename: http://192.168.0.8:1880/Doorbell/Sound-of-a-doorbell.mp3

plays nice on the Sonos.
So only the Polly thing won't

**Comment by Supergiovane** [comment]
That's important. So you have the endpoint "Doorbell" that Sonos can reach?
The node doesn't create a "Doorbell" endpoint. Have you edited something by hands?

**Comment by JorinL** [comment]
Hehe it is not an endpoint - its a normal mp3 file I use since ages to play it on a connected speaker.
I just used an inject node with this string "http://192.168.0.8:1880/Doorbell/Sound-of-a-doorbell.mp3" against the sonospollytts node. No polly function used here.

Nothing edited by hand.

**Comment by Supergiovane** [comment]
OK! Will take a look

**Comment by JorinL** [comment]
> If you inject that, the node again read the doorbell.mp3 and creates a tts endpoint. So this part does work.

If i inject the doorbell.mp3 it works and I see @sonos:
![grafik](https://user-images.githubusercontent.com/33031729/67498705-3495f380-f680-11e9-86d3-8b625783aea9.png)
Yep works. Plays and done.

> Can you confirma that:If you inject something like {payload:"Hallo, wie geht es ihnen"), it creates the mp3 and you can play it out of node-red by double clicking on it?

Can't confirm. Injecting "Hallo, wie geht es ihnen" creates the mp3 (which is playable) and copies the hailing.mp3 into /tmp, but then Sonos says:
![grafik](https://user-images.githubusercontent.com/33031729/67499219-006f0280-f681-11e9-91f7-d60438f1c1a5.png)
![grafik](https://user-images.githubusercontent.com/33031729/67499243-0b299780-f681-11e9-8c73-6d25f05b53f2.png)

**Comment by Supergiovane** [comment]
Ok, thanks.
I'll check and revert. Please leave me some time, because i'm working to release today an update version of another my node knx-ultimate. Thank i'll take a look after dinner or tomorrow. 
Sorry for that, but i'm concentrated on another node and i cannot have two things at the same time (i'm not multitasking anymore).

**Comment by JorinL** [comment]
Hey no problem ;-) 
At least you care - thanks for that :-)

**Comment by Supergiovane** [comment]
For what i can see, if the last thing on the log is "...is downloading, exit", it seems that the node cannot reach the Amazon AWS Apis to download the file. 
Do you maybe have a firewall blocking something ?

**Comment by JorinL** [comment]
But the mp3 from AWS is there - and also payable.

**Comment by Supergiovane** [comment]
Yes, but it seems not able to close the connection, thus it goes in timeout, but ok, let me find out more... I suspect i must use a docker too, otherwise it works everytime. A question: do you have updated the node-red itself? I know that docker images are everytime out of date.

**Comment by JorinL** [comment]
Eh ;-) Thats a bot of a prejudice :-)

My Dockerimage comes directly from Node-Red - running Node-Red 1.0.1: Maintenance Release

**Comment by JorinL** [comment]
Hehe ;-) using docker means also keeping with the timeline and up to date :-) (In my personal way)

Thanks for the investigation and Time! :-)

If i can help - let me know.

**Comment by Supergiovane** [comment]
Hello, what's your name? Mine is Massimo.

I'm back to you. The knx-ultimate node has been deployed, so yet i've time for you.
I've installed the docker image.
I've set the port on docker to 1880
I've set up sonospollytts with Marlene.
Bang, it works.
Can i see your docker network configuration? Mine is like this:
![NAS](https://user-images.githubusercontent.com/37666636/67504845-7166e800-f68a-11e9-9c27-1aa5b729b5a6.png)

**Comment by JorinL** [comment]
Hey Massimo, I'm Jorin

My Setup looks like this (Rancher is a bit more then only Docker):
[image: grafik.png]


Am Do., 24. Okt. 2019 um 18:16 Uhr schrieb Supergiovane <
notifications@github.com>:

**Comment by JorinL** [comment]
![grafik](https://user-images.githubusercontent.com/33031729/67506474-62ce0000-f68d-11e9-8f82-7c24570f1858.png)

**Comment by Supergiovane** [comment]
No, all required depencendies are automatically downloaded by the package installer. 
Network seems to be ok. 
I never heard about Kubernetes. I haven’t any chances to try it, but it should run like my qnap container station. 
I’ll try some “blind” test tomorrow, to try to figure out what the problem can be.

**Comment by Supergiovane** [comment]
Hallo Jorin,
i need to reproduce your environment, because all test i've done, are either passed or are throwing a visible error in the node red log.
But before that, are you able to extract and copy this file into your 

> .node-red/node_modules/node-red-contrib-sonospollytts/sonospollytts

folder, and let me know if somethings changes?

[sonospollytts.js.zip](https://github.com/Supergiovane/node-red-contrib-sonospollytts/files/3770765/sonospollytts.js.zip)

**Comment by Supergiovane** [comment]
Hallo Jorin
i've added some debug log.
Can you extract the attached file and copy it into this folder?

> .node-red/node_modules/node-red-contrib-sonospollytts/sonospollytts

Then, please try "Hallo wie geht es ihnen" and post me the log.
Thanks.

**Comment by JorinL** [comment]
Good morning :-)

`25 Oct 07:52:30 - [info] Starting flows
25 Oct 07:52:30 - [info] SonosPollyTTS: ConfigNode:[object Object]
25 Oct 07:52:30 - [info] SonosPollyTTS: Temp dir set to /tmp
25 Oct 07:52:30 - [info] SonosPollyTTS: Node-Red URL: http://192.168.0.8:1880
25 Oct 07:52:30 - [info] Moving hailing file hailing.mp3 to temp dir /tmp
25 Oct 07:52:30 - [info] SonosPollyTTS: Temp dir set to /tmp
25 Oct 07:52:30 - [info] SonosPollyTTS: Node-Red URL: http://192.168.0.8:1880
25 Oct 07:52:30 - [info] SonosPollyTTS: Hailing disabled
25 Oct 07:52:31 - [info] Started flows
25 Oct 07:52:31 - [info] [mqtt-broker:707c62cd.b68904] Connected to broker: mqtt://192.168.0.8:1883
Checking for Hue Bridge updates…
SoftwareUpdate {
  attributes: Attributes { attributes: { checkforupdate: true }, changed: {} }
}
Updating Hue Bridge Firmware and Lights…

First test (empty /tmp)

25 Oct 07:55:43 - [info] SonosPollyTTS: Leggi .MP3 diretto e skip polly, filename: hailing.mp3
25 Oct 07:55:44 - [info] SonosPollyTTS: HandleQueue - Polly is downloading the file, exit

Second test (files in /tmp both available)
25 Oct 07:55:59 - [info] SonosPollyTTS: Leggi .MP3 diretto e skip polly, filename: hailing.mp3
25 Oct 07:55:59 - [info] SonosPollyTTS: DEBUG - fromcache : /tmp/Hallo_pause_ wie geht es ihnen_Marlene.mp3
25 Oct 07:56:00 - [info] SonosPollyTTS: HandleQueue - Polly is downloading the file, exit`

**Comment by Supergiovane** [comment]
Thanks.
I need you to speak something that is not in the temp folder. Something like "uno due tre quattro".
Sorry and thank you for your patience!

**Comment by JorinL** [comment]
Which .js file should I take - the one from the email or the one from here? :-D
They differ.

**Comment by Supergiovane** [comment]
Hello Jorin
this one from here. I've added more "Jorin" debug logs.

[sonospollytts.js.zip](https://github.com/Supergiovane/node-red-contrib-sonospollytts/files/3771079/sonospollytts.js.zip)

**Comment by JorinL** [comment]
;-)

Ok i took that version:

`25 Oct 08:23:50 - [info] SonosPollyTTS: Leggi .MP3 diretto e skip polly, filename: hailing.mp3
25 Oct 08:23:51 - [info] SonosPollyTTS: HandleQueue - Polly is downloading the file, exit`

**Comment by Supergiovane** [comment]
Hmm.... it seems not even enter the function where i've logged "JORIN" rows. You should see some debug starting with "JORIN....".

**Comment by Supergiovane** [comment]
[sonospollytts.js.zip](https://github.com/Supergiovane/node-red-contrib-sonospollytts/files/3771169/sonospollytts.js.zip)
Can you try with this and post the entire log?

**Comment by JorinL** [comment]
My Thoughts: 
"http://192.168.0.8:1880/tts/tts.mp3?f=%2Ftmp%2Funo%20due%20tre%20quattro_Marlene.mp3"

This is a Web address which is not available - not from the localhost not from LAN. Is it used that way?

**Comment by Supergiovane** [comment]
Such address should be avaiable and if you point your browser to http://192.168.0.8:1880/tts/tts.mp3, you should download an empty (14 Byte) tts.mp3 file. 
Klappt das dir?

**Comment by Supergiovane** [comment]
No, the node creates an endpoint using the default node-red webserver. The enpoint is called "tts". Practically, it add an entry point to the standard node.red webserver.

**Comment by JorinL** [comment]
Nope not able to.

I'm using pictures and gifs inside my flows - so i have a modified setup inside the node-red web root dir.
Wait se second.

**Comment by JorinL** [comment]
Same.. 
"Cannot GET /data/public/tts/tts.mp3"

Log from latest .js
`````
node-red-docker@1.0.1 start /usr/src/node-red
node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"

25 Oct 09:03:19 - [info]

Welcome to Node-RED

===================

25 Oct 09:03:19 - [info] Node-RED version: v1.0.1

25 Oct 09:03:19 - [info] Node.js  version: v12.10.0

25 Oct 09:03:19 - [info] Linux 4.15.0-66-generic x64 LE

25 Oct 09:03:19 - [info] Loading palette nodes

25 Oct 09:03:20 - [info] Dashboard version 2.17.1 started at /ui

25 Oct 09:03:20 - [info] Settings file  : /data/settings.js

25 Oct 09:03:20 - [info] HTTP Static    : /data/public

25 Oct 09:03:20 - [info] Context store  : 'default' [module=memory]

25 Oct 09:03:20 - [info] User directory : /data

25 Oct 09:03:20 - [warn] Projects disabled : editorTheme.projects.enabled=false

25 Oct 09:03:20 - [info] Flows file     : /data/flows.json

25 Oct 09:03:20 - [info] Server now running at http://127.0.0.1:1880/admin/

25 Oct 09:03:20 - [info] Starting flows

25 Oct 09:03:20 - [info] SonosPollyTTS: ConfigNode:[object Object]

25 Oct 09:03:20 - [info] SonosPollyTTS: Temp dir set to /tmp

25 Oct 09:03:20 - [info] JORIN BEGIN

25 Oct 09:03:20 - [info] SonosPollyTTS: Node-Red URL: http://192.168.0.8:1880

25 Oct 09:03:20 - [info] Moving hailing file hailing.mp3 to temp dir /tmp

25 Oct 09:03:20 - [info] SonosPollyTTS: Temp dir set to /tmp

25 Oct 09:03:20 - [info] JORIN BEGIN

25 Oct 09:03:20 - [info] SonosPollyTTS: Node-Red URL: http://192.168.0.8:1880

25 Oct 09:03:20 - [info] SonosPollyTTS: Hailing disabled

25 Oct 09:03:21 - [info] Started flows

25 Oct 09:03:21 - [info] [mqtt-broker:707c62cd.b68904] Connected to broker: mqtt://192.168.0.8:1883

Checking for Hue Bridge updates…

SoftwareUpdate {

  attributes: Attributes { attributes: { checkforupdate: true }, changed: {} }

}

Updating Hue Bridge Firmware and Lights…

25 Oct 09:03:36 - [info] JORIN LEGGI

25 Oct 09:03:36 - [info] SonosPollyTTS: Leggi .MP3 diretto e skip polly, filename: hailing.mp3

25 Oct 09:03:36 - [info] JORIN into PlaySonos for playing /tmp/hailing.mp3

25 Oct 09:03:36 - [info] JORIN into PlaySonos after encodeURIComponent sUrl:http://192.168.0.8:1880/tts/tts.mp3?f=%2Ftmp%2Fhailing.mp3

25 Oct 09:03:36 - [info] JORIN into PlaySonos after setvolume

25 Oct 09:03:36 - [info] JORIN into PlaySonos setAVTransportURI node.sPollyState: transitioning

25 Oct 09:03:36 - [info] JORIN LEGGI

25 Oct 09:03:36 - [info] JORIN after filename = path.join(node.dir, filename); filename: /tmp/uno due tre quattro_Marlene.mp3

25 Oct 09:03:36 - [info] JORIN before synthesizeSpeech /tmp/uno due tre quattro_Marlene.mp3

25 Oct 09:03:37 - [info] SonosPollyTTS: HandleQueue - Polly is downloading the file, exit

25 Oct 09:03:37 - [info] JORIN after synthesizeSpeech /tmp/uno due tre quattro_Marlene.mp3

25 Oct 09:03:37 - [info] JORIN into PlaySonos for playing /tmp/uno due tre quattro_Marlene.mp3

25 Oct 09:03:37 - [info] JORIN into PlaySonos after encodeURIComponent sUrl:http://192.168.0.8:1880/tts/tts.mp3?f=%2Ftmp%2Funo%20due%20tre%20quattro_Marlene.mp3

25 Oct 09:03:37 - [info] JORIN into PlaySonos after setvolume

25 Oct 09:03:37 - [info] JORIN into PlaySonos setAVTransportURI node.sPollyState: transitioning

**Comment by Supergiovane** [comment]
I'll try to handle httpStatic directly in the code.

**Comment by Supergiovane** [comment]
No. It works. Sorry i had a false IP set.
It works even with 
httpStatic: '/data/public',

Do you maybe use https or authentication?

**Comment by JorinL** [comment]
No - not https

Is the entry you make to the webserver visible in the node-red config or just coming with the .js file?

**Comment by JorinL** [comment]
Ohh I found the tts.mp3

http://duffstation:1880/admin/tts/tts.mp3

So that is not coming with the changed http static :-D 
But with the AdminRoot

**Comment by Supergiovane** [comment]
No, the node itself creates the entrypoint on the fly, with the row: RED.httpAdmin.get("/tts/tts.mp3", function(req, res) 

If you cannot even use firefox to download the tts.mp3, i suspect that the node is unable to create such entry point.
I'll add some more "jorin" logs and i resend you the .js

**Comment by JorinL** [comment]
See comment above :-)

**Comment by Supergiovane** [comment]
As soon i changed AdminRoot, it won't work anymore.
Ok, i've a base to start!
Thank you. I revert to you soon.

**Comment by Supergiovane** [comment]
Ok, found where to put my hands in.
As soon as terminated, i'll send you the .js 
If all is ok, i'll release a new version with the updated patch,

**Comment by Supergiovane** [comment]
Bist du so nett sein, um diesen .js zu prüfen?

[sonospollytts.js.zip](https://github.com/Supergiovane/node-red-contrib-sonospollytts/files/3771485/sonospollytts.js.zip)

**Comment by JorinL** [comment]
PRETTY! :-) ! Wundervoll!

Es funktioniert!

Working! :-) Thank your very much!

**Comment by Supergiovane** [comment]
V. 1.0.20 is out.
Vielen Dank dir für deine Hilfe! Gruß

**Comment by JorinL** [comment]
Thanks for your work and time :-)

**Comment by Supergiovane** [comment]
Hello Jorin
sorry to bother. I had another user with another type of issue, so i made a more universal fix.
Can you try this file and let me know, if it works for you? Thank you.

[sonospollytts.js.zip](https://github.com/Supergiovane/node-red-contrib-sonospollytts/files/3777912/sonospollytts.js.zip)

**Comment by Supergiovane** [comment]
Nevermind, already published the update.

**Comment by JorinL** [comment]
Hehe :-D Well @Work I don't have my SONOS available :-D
