### ISSUE TITLE
Haling -> No mp3 is created for using that

### ISSUE THREAD

**Issue by JorinL** [Supergiovane/node-red-contrib-sonospollytts#22]
For "computer call" the 2.mp3 ist created - but for hailing just nothing happens O_o?

**Comment by JorinL** [comment]
I have to corretd that - using hailing after install does nothing - switching to computer call and using it and then switchtig back to hailing lets the "hailing.mp3" appear :-)

**Comment by Supergiovane** [comment]
Hello JorinL,
thanks for the feedback, but it's the first time i heard about this issue.
