### ISSUE TITLE
Speech never plays: SonosPollyTTS: HandleQueue2 - stopping: playing Track:x-rincon:RINCON_XXXXXXXXXXX

### ISSUE THREAD

**Issue by ukmoose** [Supergiovane/node-red-contrib-sonospollytts#23]
I upgraded to v1.0.20 with NR v1.0.2  when I send a payload to the node

If the Sonos is in a group the speech used to play, but now it doesn't

I get the following in the Node-RED log
SonosPollyTTS: HandleQueue2 - stopping: playing Track:x-rincon:RINCON_XXXXXXXXXX twice a second but the speech never plays.

This occurs when the sonos irrespective of if the group is actually playing anything.

If I remove the sonos from a group then the node works and the speech plays.

many thanks

Mark

**Comment by Supergiovane** [comment]
Hello
Does the v.1.0.19 works?
Do you have the problem only with 1.0.20?

**Comment by ukmoose** [comment]
I downgraded and tested and it works in fine if the sonos is in a group in v1.0.19

**Comment by Supergiovane** [comment]
Hmmm... tomorrow i’ll take a look and let you know!

**Comment by Supergiovane** [comment]
Hello Mark
can you please paste here the screenshot of your Sonospollytts node config? 
Thanks

**Comment by ukmoose** [comment]
Wow you are fast!   
Yes that fixes the issue, many thanks.

**Comment by Supergiovane** [comment]
Ok, please keep all as is. I need to do some more tests, then i'll release the v.1.0.21
Thank you for your feedback!

**Comment by Supergiovane** [comment]
Hello Mark
does Sonospollytts works with Groups?
I've done some changes and i need someone using groups.
