### ISSUE TITLE
Sonos Speakers in Group Give "pausing error"

### ISSUE THREAD

**Issue by Flight777** [Supergiovane/node-red-contrib-sonospollytts#26]
So another thing that I noticed:

If speakers have been in a group playing music, Sonos will retain this group for a while (even though it's not playing anything anymore).

However, somehow the plugin is not handling groups well, whenever a speaker is in the group and it's trying to server TTS or MP3s, in node-red it will blink "pausing error" on and off under the node. In the logs it reads as followed:

```
13 Nov 22:40:26 - [info] SonosPollyTTS: HandleQueue2 - stopping: playing Track:x-rincon:RINCON_7828CA02FBCE01400

13 Nov 22:40:26 - [info] SonosPollyTTS: HandleQueue2 - stopping: playing Track:x-rincon:RINCON_7828CA02FBCE01400

13 Nov 22:40:27 - [info] SonosPollyTTS: HandleQueue2 - stopping: playing Track:x-rincon:RINCON_7828CA02FBCE01400

13 Nov 22:40:27 - [info] SonosPollyTTS: HandleQueue2 - stopping: playing Track:x-rincon:RINCON_7828CA02FBCE01400

13 Nov 22:40:28 - [info] SonosPollyTTS: HandleQueue2 - stopping: playing Track:x-rincon:RINCON_7828CA02FBCE01400

13 Nov 22:40:28 - [info] SonosPollyTTS: HandleQueue2 - stopping: playing Track:x-rincon:RINCON_7828CA02FBCE01400

13 Nov 22:40:29 - [info] SonosPollyTTS: HandleQueue2 - stopping: playing Track:x-rincon:RINCON_7828CA02FBCE01400

13 Nov 22:40:30 - [info] SonosPollyTTS: HandleQueue2 - stopping: playing Track:x-rincon:RINCON_7828CA02FBCE01400

13 Nov 22:40:30 - [info] SonosPollyTTS: HandleQueue2 - stopping: playing Track:x-rincon:RINCON_7828CA02FBCE01400

13 Nov 22:40:31 - [info] SonosPollyTTS: HandleQueue2 - stopping: playing Track:x-rincon:RINCON_7828CA02FBCE01400

13 Nov 22:40:31 - [info] SonosPollyTTS: HandleQueue2 - stopping: playing Track:x-rincon:RINCON_7828CA02FBCE01400

13 Nov 22:40:32 - [info] SonosPollyTTS: HandleQueue2 - stopping: playing Track:x-rincon:RINCON_7828CA02FBCE01400

13 Nov 22:40:32 - [info] SonosPollyTTS: HandleQueue2 - stopping: playing Track:x-rincon:RINCON_7828CA02FBCE01400

13 Nov 22:40:33 - [info] SonosPollyTTS: HandleQueue2 - stopping: playing Track:x-rincon:RINCON_7828CA02FBCE01400
```

This will continue indefintely until I either break the group in the Sonos app, redeploy the flow or restart Node-Red.

So the core problem, it's somehow not able to handle (or break) the groups, but at least it should time-out after XX seconds or XX tries maybe? Because now it can completely overload Node-Red.

If more info is needed, please let me know how I can troubleshoot and happy to help!

**Comment by Supergiovane** [comment]
Hello,
the group problem is known. I've only a Sonos AMP and a subwoofer grouped, but mine is working. How many device do you have in your group?

**Comment by Flight777** [comment]
I have 10 Sonos speakers. In this case it tried to TTS to 1 Sonos One speaker that was in a group with another Sonos One from earlier during the day. So a group of 2 as well.

**Comment by Supergiovane** [comment]
Hmmm..... maybe my Subwoofer and Sonos AMP are working in a different way than two or more speakers.
Unless i've another Sonos Speaker, i cannot try and fix the issue. I'll go buy another sonos speaker and i'll try. Sorry and please be patient...

**Comment by Supergiovane** [comment]
PS: Thank you for the paypal donation!

**Comment by Flight777** [comment]
@Supergiovane No problem, thanks for all the time you put in making this plugin for us all :)

If you'd like I can create you a vpn to my network so you can do some testing? Saves you buying additional speakers (unless you need a good reason to finally have permission for more Sonos from a better half ;-) )

**Comment by Supergiovane** [comment]
It seems a good idea. OpenVPN or what? I need only access to your node-red web page, to a ssh console to be able to restart node-red and to a **/.node-red/node_modules/node-red-contrib-sonospollytts** folder, to be able to upload somethings.

**Comment by Supergiovane** [comment]
..or a VNC session, or an RDP session should be OK as well.

**Comment by Flight777** [comment]
I'll arrange access tonight when home from work. Is there any way I can send you the detail in a PM of some sorts?

**Comment by Supergiovane** [comment]
You can write an email here 
info@supergiovane.it
Thanks.

**Comment by Flight777** [comment]
See e-mail for details!

**Comment by Supergiovane** [comment]
Are you alive?
