### ISSUE TITLE
Error while playing something

### ISSUE THREAD

**Issue by mschoenel** [Supergiovane/node-red-contrib-sonospollytts#29]
If I want to send a message to a sonos device which is currently playing something (musik playlist or a radio station) it gets an error: "connect ETIMEOUT IP ADRESS"

In general it whould be nice if the message could play during the sonos device is something playing. After the message it should be continued with the same Playlist.

**Comment by Supergiovane** [comment]
Hello
It should do what you say. 
I’ll take a look.

**Comment by mschoenel** [comment]
Hello, thank you for your quick answer. 
I have several Sonos1 and one Sonos 5 speakers and one Sonos Playbar in use.
If I send a message to the Sonos 1 player the played playlist will stop and the message will played. But afterwards it's not starting the playlist again....

**Comment by Supergiovane** [comment]
Hello
Yes, this is an intended behaviour. Sonospollytts doesn’t know wich playlist or song are you currently playing, son it cannot tell sonos to resume. You should use the Sonos Node to resume the playback, by monitoring the output of the sonospollytts node (it emits a msg whenever it end speaking).

**Comment by mschoenel** [comment]
Ok Thanks..I have this implemented.
But sometimes the Sonospollytts Node is displaying an Error with the Connection. 
This happens several times...
May be it lost the Connection but the Timeout to Show an Error is to low....
