### ISSUE TITLE
Take Sonos snapshot and resume after TTS plays

### ISSUE THREAD

**Issue by rephlex00** [Supergiovane/node-red-contrib-sonospollytts#3]
Would it possible for this node to take a snapshot (similar to the Home Assistant [component](https://www.home-assistant.io/components/sonos/#service-sonos_snapshot)) of the targeted speaker's current volume and session prior to TTS and resume that snapshot afterwards?

For example, as of now if I am listening to music on the targeted Sonos speaker the TTS will play, the music will stop, and the volume will retain it's TTS value.

Ideally, when the speaker is playing music at volume level 15 and the TTS plays at volume level 50, it would be nice if the speaker resumed what it was playing at volume level 15 after the TTS.

Thank you, and great work!

**Comment by Supergiovane** [comment]
Hello,
i'll give it a shot, but the plugin is intended to be used as TTS only gateway.

**Comment by rephlex00** [comment]
Thank you very much.  I've tried to adapt it to my needs with the node-red-contrib-better-sonos but unfortunately there are bugs in node-sonos that make it very frustrating to work with (http/500 errors) and the inability to resume a track.  I've forked your repo and will try to make some small changes myself, but at best I'm only an amateur programmer so I'll certainly let you review my additions before I even attempt a pull request.

Thank you again.

**Comment by mfw2010** [comment]
I’m trying to do exactly this. Did anyone have any success achieving playback resume after TTS?

**Comment by Supergiovane** [comment]
Hi mfw,
you can use the output pin of SonosPollyTTS to detect when it finished speaking and linking it to another sono's node.
SonosPollyTTS is not aimed to handle playback/resuming of music. You need to use another sonos node beside SonosPollyTTS.

**Comment by mfw2010** [comment]
Thanks for the prompt response. I have been trying since to get this to work. I noticed there is a msg.complete which is useful but I am struggling to see which node gives me a snapshot and how I can resume it in the correct Sonos speaker. Any pointers would be very helpful!

**Comment by Supergiovane** [comment]
Hi mfw
Unfortunately, i’m unable to find any node allowing such thing of snapshot!

**Comment by mfw2010** [comment]
Hi Supergiovane
I tinkered around and copied from other nodes i had from a different package.
The below flow uses a combination of Sonos Polly, Sonos Plus to resume. The particular flow announces the time using simpletime node every hour.

`[{"id":"25e90d6d.ef48f2","type":"inject","z":"5d031d50.ab2b44","name":"CuckooTime","topic":"queueBackup","payload":"remove.sonosplaylist","payloadType":"str","repeat":"","crontab":"0 7-16 * * *","once":false,"onceDelay":0.1,"x":140,"y":140,"wires":[["9d026450.049f68"]]},{"id":"bae75384.60183","type":"comment","z":"5d031d50.ab2b44","name":"Hourly Chime Sound","info":"Plays the big ben chime followed by the time announced in hh AM/PM format. Uses a combimation of SonosPolly and SonosPlus to resume playback queue on completion of announcement","x":130,"y":60,"wires":[]},{"id":"728f4ddb.9029e4","type":"simpletime","z":"5d031d50.ab2b44","name":"","x":1570,"y":140,"wires":[["71a52d74.2908d4"]]},{"id":"71a52d74.2908d4","type":"change","z":"5d031d50.ab2b44","name":"payload","rules":[{"t":"set","p":"payload","pt":"msg","to":"myhourpm & mypm","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":1720,"y":140,"wires":[["f0ede284.b2c96"]]},{"id":"b31a8760.aeb1f8","type":"sonospollytts","z":"5d031d50.ab2b44","name":"","voice":"0","ssml":false,"sonosipaddress":"192.168.1.64","sonosvolume":"35","sonoshailing":"Hailing_bigben.mp3","config":"","property":"payload","propertyType":{},"rules":[],"x":2100,"y":200,"wires":[["98cc8334.a152"]]},{"id":"bd05b2ff.b7ed8","type":"change","z":"5d031d50.ab2b44","name":"create snapshot","rules":[{"t":"set","p":"payload","pt":"msg","to":"create.snap","tot":"str"},{"t":"set","p":"snapVolumes","pt":"msg","to":"true","tot":"bool"},{"t":"set","p":"snapMutestates","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":880,"y":140,"wires":[["137928d1.8c0cb7"]]},{"id":"68a934ce.0363ac","type":"sonos-universal","z":"5d031d50.ab2b44","confignode":"6bcd8b37.118004","name":"Kitchen","x":3120,"y":200,"wires":[["d8470a1b.ff86b8"]]},{"id":"d8470a1b.ff86b8","type":"debug","z":"5d031d50.ab2b44","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":3250,"y":200,"wires":[]},{"id":"e22f82a5.a198e","type":"change","z":"5d031d50.ab2b44","name":"store in flow, stop","rules":[{"t":"set","p":"recentsnapshot","pt":"flow","to":"payload","tot":"msg"},{"t":"set","p":"payload","pt":"msg","to":"stop","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1250,"y":140,"wires":[["11a8a5ca.b8e03a"]]},{"id":"f0194b94.f3a2f8","type":"change","z":"5d031d50.ab2b44","name":"play snapshot","rules":[{"t":"set","p":"payload","pt":"msg","to":"play.snap","tot":"str"},{"t":"set","p":"snap","pt":"msg","to":"recentsnapshot","tot":"flow"}],"action":"","property":"","from":"","to":"","reg":false,"x":2960,"y":200,"wires":[["68a934ce.0363ac"]]},{"id":"6a8856f2.12a568","type":"sonos-manage-mysonos","z":"5d031d50.ab2b44","confignode":"6bcd8b37.118004","name":"Kitchen","x":2800,"y":200,"wires":[["f0194b94.f3a2f8"]]},{"id":"7c59dfce.14c61","type":"sonos-universal","z":"5d031d50.ab2b44","confignode":"6bcd8b37.118004","name":"Kitchen","x":2520,"y":200,"wires":[["26467262.0999de"]]},{"id":"26467262.0999de","type":"change","z":"5d031d50.ab2b44","name":"restoreQ","rules":[{"t":"set","p":"payload","pt":"msg","to":"queue","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"queueBackup","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":2660,"y":200,"wires":[["6a8856f2.12a568"]]},{"id":"9c949b8d.79a1a8","type":"change","z":"5d031d50.ab2b44","name":"backup queue","rules":[{"t":"set","p":"payload","pt":"msg","to":"save.queue","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"queueBackup","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":520,"y":140,"wires":[["e634b3cf.5e651"]]},{"id":"9d026450.049f68","type":"sonos-universal","z":"5d031d50.ab2b44","confignode":"6bcd8b37.118004","name":"Kitchen","x":340,"y":140,"wires":[["9c949b8d.79a1a8"]]},{"id":"e634b3cf.5e651","type":"sonos-universal","z":"5d031d50.ab2b44","confignode":"6bcd8b37.118004","name":"Kitchen","x":700,"y":140,"wires":[["bd05b2ff.b7ed8"]]},{"id":"137928d1.8c0cb7","type":"sonos-universal","z":"5d031d50.ab2b44","confignode":"6bcd8b37.118004","name":"Kitchen","x":1060,"y":140,"wires":[["e22f82a5.a198e"]]},{"id":"11a8a5ca.b8e03a","type":"sonos-universal","z":"5d031d50.ab2b44","confignode":"6bcd8b37.118004","name":"Kitchen","x":1420,"y":140,"wires":[["728f4ddb.9029e4"]]},{"id":"98cc8334.a152","type":"switch","z":"5d031d50.ab2b44","name":"played","property":"completed","propertyType":"msg","rules":[{"t":"true"}],"checkall":"true","repair":false,"outputs":1,"x":2270,"y":200,"wires":[["2a70e346.fe916c"]]},{"id":"2a70e346.fe916c","type":"change","z":"5d031d50.ab2b44","name":"clearQ","rules":[{"t":"set","p":"payload","pt":"msg","to":"clear.queue","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":2390,"y":200,"wires":[["7c59dfce.14c61"]]},{"id":"f0ede284.b2c96","type":"time-switch","z":"5d031d50.ab2b44","name":"timeswitch","lat":"52.028728","lon":"-0.698990","startTime":"17:15","endTime":"06:00","startOffset":0,"endOffset":0,"x":1890,"y":140,"wires":[["ecd3e66c.b041c8"],["b31a8760.aeb1f8"]]},{"id":"ecd3e66c.b041c8","type":"sonospollytts","z":"5d031d50.ab2b44","name":"","voice":"0","ssml":false,"sonosipaddress":"192.168.1.64","sonosvolume":"20","sonoshailing":"Hailing_bigben.mp3","config":"","property":"payload","propertyType":{},"rules":[],"x":2100,"y":80,"wires":[["ed2d2d85.10df2"]]},{"id":"2242947d.d6facc","type":"sonos-universal","z":"5d031d50.ab2b44","confignode":"6bcd8b37.118004","name":"Kitchen","x":3120,"y":80,"wires":[["189347ac.ec12a8"]]},{"id":"189347ac.ec12a8","type":"debug","z":"5d031d50.ab2b44","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":3250,"y":80,"wires":[]},{"id":"fe8a0588.b90c58","type":"change","z":"5d031d50.ab2b44","name":"play snapshot","rules":[{"t":"set","p":"payload","pt":"msg","to":"play.snap","tot":"str"},{"t":"set","p":"snap","pt":"msg","to":"recentsnapshot","tot":"flow"}],"action":"","property":"","from":"","to":"","reg":false,"x":2960,"y":80,"wires":[["2242947d.d6facc"]]},{"id":"21086d8f.01b0c2","type":"sonos-manage-mysonos","z":"5d031d50.ab2b44","confignode":"6bcd8b37.118004","name":"Kitchen","x":2800,"y":80,"wires":[["fe8a0588.b90c58"]]},{"id":"cd812e24.38d2a","type":"sonos-universal","z":"5d031d50.ab2b44","confignode":"6bcd8b37.118004","name":"Kitchen","x":2520,"y":80,"wires":[["e2d3121c.d17c7"]]},{"id":"e2d3121c.d17c7","type":"change","z":"5d031d50.ab2b44","name":"restoreQ","rules":[{"t":"set","p":"payload","pt":"msg","to":"queue","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"queueBackup","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":2660,"y":80,"wires":[["21086d8f.01b0c2"]]},{"id":"ed2d2d85.10df2","type":"switch","z":"5d031d50.ab2b44","name":"played","property":"completed","propertyType":"msg","rules":[{"t":"true"}],"checkall":"true","repair":false,"outputs":1,"x":2270,"y":80,"wires":[["8c582b07.bfce88"]]},{"id":"8c582b07.bfce88","type":"change","z":"5d031d50.ab2b44","name":"clearQ","rules":[{"t":"set","p":"payload","pt":"msg","to":"clear.queue","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":2390,"y":80,"wires":[["cd812e24.38d2a"]]},{"id":"6bcd8b37.118004","type":"sonos-config","z":"","name":"SonosKitchen","serialnum":"","ipaddress":""}]`

**Comment by Supergiovane** [comment]
Wow!

**Comment by Cafun** [comment]
Hi @mfw2010 ,
Thank you for your flow! However at the sonosplus universal node the "command" option is empty and I cannot find out what to select for command at every node.
The first sonosplus universal node would be "player: get queue", but what in the next nodes?

Can you help me with that?

**Comment by mfw2010** [comment]
Hi @Cafun 
Apologies for the late reply and not sure if you already addressed this.

I had to modify the universal nodes to include commands as the sonosplus packages had a major update. Attached is my new flow:


`[{"id":"c8ef0fe.2d6d7f","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"474d91df.4c874","type":"inject","z":"c8ef0fe.2d6d7f","name":"CuckooTime","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"0 7-19 * * *","once":false,"onceDelay":0.1,"x":140,"y":320,"wires":[["3202aa25.a1ef06"]]},{"id":"cbde9415.bd5618","type":"simpletime","z":"c8ef0fe.2d6d7f","name":"","x":1430,"y":320,"wires":[["30e98e92.094b02"]]},{"id":"4768d12.c726b3","type":"sonospollytts","z":"c8ef0fe.2d6d7f","name":"","voice":"0","ssml":false,"sonosipaddress":"192.168.1.64","sonosvolume":"35","sonoshailing":"Hailing_bigben.mp3","config":"c00e0962.876fc8","property":"payload","propertyType":{},"rules":[],"x":1940,"y":320,"wires":[["11e91728.044509"]]},{"id":"241dcfd8.47443","type":"change","z":"c8ef0fe.2d6d7f","name":"store in flow, stop","rules":[{"t":"set","p":"recentsnapshot","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":1130,"y":320,"wires":[["b3f48f61.0de1"]]},{"id":"3202aa25.a1ef06","type":"sonos-universal","z":"c8ef0fe.2d6d7f","confignode":"f7d22c5f.f8cce","compatibilityMode":false,"command":"household.remove.sonosplaylist","state":"queueBackup","stateType":"str","name":"RemoveSonosPlaylist","x":340,"y":320,"wires":[["6c90ac97.e46bd4"]]},{"id":"3196ce4f.e1aaa2","type":"sonos-universal","z":"c8ef0fe.2d6d7f","confignode":"f7d22c5f.f8cce","compatibilityMode":false,"command":"group.create.snap","state":"","stateType":"str","name":"createSnap","x":930,"y":320,"wires":[["241dcfd8.47443"]]},{"id":"b3f48f61.0de1","type":"sonos-universal","z":"c8ef0fe.2d6d7f","confignode":"f7d22c5f.f8cce","compatibilityMode":false,"command":"group.stop","state":"","stateType":"str","name":"Stop","x":1290,"y":320,"wires":[["cbde9415.bd5618"]]},{"id":"11e91728.044509","type":"switch","z":"c8ef0fe.2d6d7f","name":"played","property":"completed","propertyType":"msg","rules":[{"t":"true"}],"checkall":"true","repair":false,"outputs":1,"x":2110,"y":320,"wires":[["14e4046e.8eaaec"]]},{"id":"33dcc524.4e3c0a","type":"change","z":"c8ef0fe.2d6d7f","name":"snapVolume","rules":[{"t":"set","p":"snapVolumes","pt":"msg","to":"true","tot":"bool"},{"t":"set","p":"snapMutestates","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":750,"y":320,"wires":[["3196ce4f.e1aaa2"]]},{"id":"14e4046e.8eaaec","type":"sonos-universal","z":"c8ef0fe.2d6d7f","confignode":"f7d22c5f.f8cce","compatibilityMode":false,"command":"group.clear.queue","state":"","stateType":"str","name":"clearQueue","x":2270,"y":320,"wires":[["464b7828.863158"]]},{"id":"6c90ac97.e46bd4","type":"sonos-universal","z":"c8ef0fe.2d6d7f","confignode":"f7d22c5f.f8cce","compatibilityMode":false,"command":"group.save.queue","state":"","stateType":"str","name":"","x":550,"y":320,"wires":[["33dcc524.4e3c0a"]]},{"id":"30e98e92.094b02","type":"switch","z":"c8ef0fe.2d6d7f","name":"chkMinute","property":"myminute","propertyType":"msg","rules":[{"t":"eq","v":"00","vt":"str"},{"t":"neq","v":"00","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":1590,"y":320,"wires":[["7194d45c.6a1bfc"],["2439b8cb.654b88"]]},{"id":"7194d45c.6a1bfc","type":"change","z":"c8ef0fe.2d6d7f","name":"payload","rules":[{"t":"set","p":"payload","pt":"msg","to":"myhourpm & \" \" & mypm","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":1760,"y":280,"wires":[["4768d12.c726b3"]]},{"id":"2439b8cb.654b88","type":"change","z":"c8ef0fe.2d6d7f","name":"payload","rules":[{"t":"set","p":"payload","pt":"msg","to":"myhourpm & \" \" & myminute & \" \" & mypm","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":1760,"y":360,"wires":[["4768d12.c726b3"]]},{"id":"464b7828.863158","type":"sonos-manage-mysonos","z":"c8ef0fe.2d6d7f","confignode":"f7d22c5f.f8cce","compatibilityMode":false,"command":"mysonos.queue.item","state":"queueBackup","stateType":"str","name":"Queue","x":2410,"y":320,"wires":[["d2e0d361.51647"]]},{"id":"d2e0d361.51647","type":"change","z":"c8ef0fe.2d6d7f","name":"restore from flow","rules":[{"t":"set","p":"payload","pt":"msg","to":"recentsnapshot","tot":"flow"}],"action":"","property":"","from":"","to":"","reg":false,"x":2590,"y":320,"wires":[["a3a66e6e.77782"]]},{"id":"a3a66e6e.77782","type":"sonos-universal","z":"c8ef0fe.2d6d7f","confignode":"f7d22c5f.f8cce","compatibilityMode":false,"command":"group.play.snap","state":"","stateType":"str","name":"","x":2800,"y":320,"wires":[[]]},{"id":"c00e0962.876fc8","type":"sonospollytts-config","z":"","name":"Config","noderedipaddress":"192.168.1.205","noderedport":"1981","purgediratrestart":"leave"},{"id":"f7d22c5f.f8cce","type":"sonos-config","z":"","name":"SonosKitchen","serialnum":"B8-E9-37-B8-23-B6:E","ipaddress":"192.168.1.64"}]`

Hope this works for you

**Comment by Cafun** [comment]
Hi @mfw2010 !
Don't appologise! It's not that late you replied!

Thank you so much! This works!
