### ISSUE TITLE
Request: Dynamically select hailing sound

### ISSUE THREAD

**Issue by Flight777** [Supergiovane/node-red-contrib-sonospollytts#32]
Would it be possible to implement also a dynamic config option for the hailing sound? That depending on the message, you can set 1,2 or 3?

**Comment by Supergiovane** [comment]
Hi
Yes and thenidea is to leave the user to upload custom hailing sounds as well. Please leave me some time, because here we’ve big issues in Italy with coronavirus.

**Comment by Supergiovane** [comment]
Out today with V. 1.1.14

**Comment by Flight777** [comment]
Wow brilliant, that was fast! The upload is not fully working for me yet, but when I manually add them in the folder they show up :)

You are not in Northern Italy I hope??

**Comment by Supergiovane** [comment]
Yes i am. Starting from tonight, the while Italy has become red zone. We cannot go out. We must close our jobs. I must find a way to find the incomings for my family. 
That’s not good. 
I’ll try tomorrow to fix it. Sorry.

**Comment by Supergiovane** [comment]
Hello,
tried yet. Upload of hailing files works. Please use only mp3 files.
