### ISSUE TITLE
handling file audio error

### ISSUE THREAD

**Issue by barto95100** [Supergiovane/node-red-contrib-sonospollytts#36]
Hi, 

I test your node on node-red hassio

when I test to add a audio file on node ownfile (jingle.mp3) a received the Error

do you have idea of the problem ? 

thank's

**Comment by Supergiovane** [comment]
Hi Barto
What error do you receive?

**Comment by barto95100** [comment]
Hi want to Send an Audio file to annonce the annoncement and send the TTS to Sonos 

Maybe I don't understand how it's work

**Comment by Supergiovane** [comment]
Hello 
Do you have followed the sample? There is a sample code you can paste into your flow. Please see the readme on github.

**Comment by barto95100** [comment]
Yes Copy your sample 

but, when I test add my hailling song the song is not in the dropdown lost

**Comment by Supergiovane** [comment]
It can be that you have auth problems with hassio. 
You should allow node-red to wrote to the filesystem. You should ask to the hassio community how to do that.
