### ISSUE TITLE
Temperatur announced via Alexa

### ISSUE THREAD

**Issue by niwre2019** [Supergiovane/node-red-contrib-sonospollytts#38]
Hi,
I would like to have several temperatures announced over Alexa.  Unfortunately, due to the many different temperatures, many MP3 files are created.  Therefore I would like to delete the files regularly, but I do not know whether this could lead to problems because the file is no longer found in the cache at the same temperature.  Can I do it easily or does it cause problems?
Regards
Niwre

**Comment by Supergiovane** [comment]
Hi Niwre,
Yes, you can delete it without issues. The next time, the node will create the TTS and download the mp3 again, if necessary.
I suggest you not to delete the files, because every call to AWS Amazon service, after some numbers of requests, will cost you money on every call.
