### ISSUE TITLE
Boot Loop if Sonos Hailing is Disabled

### ISSUE THREAD

**Issue by cburgdorfer** [Supergiovane/node-red-contrib-sonospollytts#4]
If I disable the "hailing", node red seems to get stuck in a booting loop with the error message:

```Error: EISDIR: illegal operation on a directory, open '/tmp'```

Temporary resolution is restoring the backup flow.

**Comment by Supergiovane** [comment]
Thank you for your report. 
Are you on Raspberry pi or not?

**Comment by cburgdorfer** [comment]
It was on a Raspberry Pi. It seems to work now. Not sure what the problem was. I will observe and get back here if it happens again. Thanks for your response, much appreciated!
