### ISSUE TITLE
Sonos players in other subnet

### ISSUE THREAD

**Issue by georgr** [Supergiovane/node-red-contrib-sonospollytts#40]
My Sonos players are living in another subnet, therefore it is not possible to discover them via mdns/zeroconf. It would be nice if there was an option to configure the Sonos players alternatively via ip addresses or hostnames.

**Comment by Supergiovane** [comment]
Hi
It is already so. If you ipen the config window and the node cannot discover any sonos device, after ca. 10 seconds a textbox appear. Here you can enter the sonos IP.
