### ISSUE TITLE
SSML payload causes error in file-path

### ISSUE THREAD

**Issue by s1x** [Supergiovane/node-red-contrib-sonospollytts#41]
The following payload with SSML produces the following error:

Payload:
`'<speak>Guten Morgen! Gerade sind es <emphasis level="strong">' & roofTemp &	 ' Grad</emphasis> draußen.</speak>'`

`"SonosPollyTTS: notifyError - msg: /opt/iobroker/iobroker-data/node-red//sonospollyttsstorage/ttsfiles/_less_speak_greater_Guten Morgen_em_ Gerade sind es _less_emphasis level="strong"_greater_25 Grad_less_/emphasis_greater_ draußen_stop__less_/speak_greater__Hans_ssml.mp3 error: ENOENT: no such file or directory, open '/opt/iobroker/iobroker-data/node-red//sonospollyttsstorage/ttsfiles/_less_speak_greater_Guten Morgen_em_ Gerade sind es _less_emphasis level="strong"_greater_25 Grad_less_/emphasis_greater_ draußen_stop__less_/speak_greater__Hans_ssml.mp3'"`

Without using SSML (and therefore the <speak> tags) it is working fine.

**Comment by Supergiovane** [comment]
Hi Julian
sonospollytts doesn't support emphasis at this time. You need to pass simple texts, for example "Guten Morgen! Gerade sind es 24 Grad draußen.", without the "<" and ">" brackets.

**Comment by s1x** [comment]
Hey,

but that means I cannot use SSML, correct?

**Comment by Supergiovane** [comment]
Yes, sorry, i mean SSML. 
As soon as Amazon will add more SSML tags, i'll begin to work on that as well.

**Comment by s1x** [comment]
Alright, thanks for the clarification! No worries and thank you for all those great nodes!
