### ISSUE TITLE
Random Connection error on node

### ISSUE THREAD

**Issue by mfw2010** [Supergiovane/node-red-contrib-sonospollytts#42]
Hi
Everything was working fine until yesterday when I updated SonosPlus to 4.0.0. I don't know if is related but now every few seconds, the Sonos Polly TTS node refreshes and displays the below connection error. It happens regardless of which player is configured, they are all in the network and reachable...any ideas?

err currtrack: Error: connect ETIMEDOUT 192.168.1.64:1400 (18, 1:23:18 PM)

Thanks

**Comment by Supergiovane** [comment]
Hi MFW
does sononspollytts node works?

**Comment by mfw2010** [comment]
Yes, it works. But every few seconds it seems to refresh its status and then displays this error:
err currtrack: Error: connect ETIMEDOUT 192.168.1.64:1400 (18, 1:23:18 PM)

**Comment by Supergiovane** [comment]
Every xx second, the node asks sonos for the current track info.
There must be something changed in the sonos plus.
I've not updated yet, but i will soon and i'll investigate that.
Thanks for your feedback.

**Comment by Supergiovane** [comment]
Sorry for the question, do you have rebooted the node-red?

**Comment by Supergiovane** [comment]
Hi MFW 
i cannot duplicate your issue. Can you please paste here your flow (only the sonos-plus nodes) or at least take a screenshot, so i can see, what sonos-plus node are you using?
Thanks

**Comment by Supergiovane** [comment]
In the meantime, i tried to update the API to 1.13.0.
Sonospollytts V. 25 will be out in 30 minutes. Try that.

**Comment by mfw2010** [comment]
Thanks, will try that first, I'm sure it is not to do with the flow, but I'll share that in a bit as well.

**Comment by Supergiovane** [comment]
Thanks, yes i know, but i need to view what sonos-plus nodes are you using, to be able to reproduce the issue on my machine.

**Comment by mfw2010** [comment]
This is the flow...it seems to work for now after the upgrade! I'll keep an eye and see if the issue comes again.


`[{"id":"f11a4d64.917db","type":"tab","label":"Flow 4","disabled":false,"info":""},{"id":"29a577fe.9d50b8","type":"inject","z":"f11a4d64.917db","name":"BigBen","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"0 7-20 * * *","once":false,"onceDelay":0.1,"x":100,"y":140,"wires":[["dec6caa7.597b58"]]},{"id":"dd07fc0b.944d8","type":"comment","z":"f11a4d64.917db","name":"Hourly Chime Sound","info":"","x":110,"y":60,"wires":[]},{"id":"2373bee.295db42","type":"simpletime","z":"f11a4d64.917db","name":"","x":1410,"y":140,"wires":[["d3ecb019.e4441"]]},{"id":"d3ecb019.e4441","type":"change","z":"f11a4d64.917db","name":"payload","rules":[{"t":"set","p":"payload","pt":"msg","to":"myhourpm & mypm","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":1580,"y":140,"wires":[["f8e02c52.7ebec"]]},{"id":"f8e02c52.7ebec","type":"sonospollytts","z":"f11a4d64.917db","name":"","voice":"0","ssml":false,"sonosipaddress":"192.168.1.64","sonosvolume":"35","sonoshailing":"Hailing_bigben.mp3","config":"a4c62072.f66db","property":"payload","propertyType":{},"rules":[],"x":1760,"y":140,"wires":[["67c9fc2d.9aba54"]]},{"id":"edf3278e.1169c8","type":"sonos-universal","z":"f11a4d64.917db","confignode":"6bcd8b37.118004","compatibilityMode":false,"command":"group.play.snap","state":"","stateType":"str","name":"Kitchen","x":2780,"y":140,"wires":[["f5305fc0.518cf"]]},{"id":"f5305fc0.518cf","type":"debug","z":"f11a4d64.917db","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":2930,"y":140,"wires":[]},{"id":"ac200b6a.1adee8","type":"change","z":"f11a4d64.917db","name":"store in flow, stop","rules":[{"t":"set","p":"recentsnapshot","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":1110,"y":140,"wires":[["7a91075f.a1bc18"]]},{"id":"56831a1f.d04104","type":"change","z":"f11a4d64.917db","name":"play snapshot","rules":[{"t":"set","p":"snap","pt":"msg","to":"recentsnapshot","tot":"flow"}],"action":"","property":"","from":"","to":"","reg":false,"x":2600,"y":140,"wires":[["edf3278e.1169c8"]]},{"id":"aa7b1ea2.066a","type":"sonos-manage-mysonos","z":"f11a4d64.917db","confignode":"6bcd8b37.118004","name":"Kitchen","x":2420,"y":140,"wires":[["56831a1f.d04104"]]},{"id":"2721b3b8.8c70fc","type":"change","z":"f11a4d64.917db","name":"restoreQ","rules":[{"t":"set","p":"topic","pt":"msg","to":"queueBackup","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":2260,"y":140,"wires":[["aa7b1ea2.066a"]]},{"id":"dec6caa7.597b58","type":"sonos-universal","z":"f11a4d64.917db","confignode":"6bcd8b37.118004","compatibilityMode":false,"command":"household.remove.sonosplaylist","state":"queueBackup","stateType":"str","name":"RemoveSonosPlaylist","x":300,"y":140,"wires":[["fc3f1577.48a178"]]},{"id":"bd981e5.712ede","type":"sonos-universal","z":"f11a4d64.917db","confignode":"6bcd8b37.118004","compatibilityMode":false,"command":"group.create.snap","state":"","stateType":"str","name":"createSnap","x":910,"y":140,"wires":[["ac200b6a.1adee8"]]},{"id":"7a91075f.a1bc18","type":"sonos-universal","z":"f11a4d64.917db","confignode":"6bcd8b37.118004","compatibilityMode":false,"command":"group.stop","state":"","stateType":"str","name":"Stop","x":1270,"y":140,"wires":[["2373bee.295db42"]]},{"id":"67c9fc2d.9aba54","type":"switch","z":"f11a4d64.917db","name":"played","property":"completed","propertyType":"msg","rules":[{"t":"true"}],"checkall":"true","repair":false,"outputs":1,"x":1930,"y":140,"wires":[["cd22b362.cd5ff"]]},{"id":"9d88afb3.b66f","type":"change","z":"f11a4d64.917db","name":"snapVolume","rules":[{"t":"set","p":"snapVolumes","pt":"msg","to":"true","tot":"bool"},{"t":"set","p":"snapMutestates","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":730,"y":140,"wires":[["bd981e5.712ede"]]},{"id":"cd22b362.cd5ff","type":"sonos-universal","z":"f11a4d64.917db","confignode":"6bcd8b37.118004","compatibilityMode":false,"command":"group.clear.queue","state":"","stateType":"str","name":"clearQueue","x":2090,"y":140,"wires":[["2721b3b8.8c70fc"]]},{"id":"fc3f1577.48a178","type":"sonos-universal","z":"f11a4d64.917db","confignode":"8f44d2a.41b103","compatibilityMode":false,"command":"group.save.queue","state":"queueBackup","stateType":"str","name":"","x":530,"y":140,"wires":[["9d88afb3.b66f"]]},{"id":"a4c62072.f66db","type":"sonospollytts-config","z":"","name":"Config","noderedipaddress":"192.168.1.140","noderedport":"1980","purgediratrestart":"leave"},{"id":"6bcd8b37.118004","type":"sonos-config","z":"","name":"SonosKitchen","serialnum":"B8-E9-37-B8-23-B6:E","ipaddress":"192.168.1.64"},{"id":"8f44d2a.41b103","type":"sonos-config","z":"","name":"SonosLiving","serialnum":"00-0E-58-BF-B8-4E:E","ipaddress":"192.168.1.14"}]`

**Comment by mfw2010** [comment]
This is the flow. Seems to be working now but I will keep a close eye:

`[{"id":"f11a4d64.917db","type":"tab","label":"Flow 4","disabled":false,"info":""},{"id":"29a577fe.9d50b8","type":"inject","z":"f11a4d64.917db","name":"BigBen","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"0 7-20 * * *","once":false,"onceDelay":0.1,"x":100,"y":140,"wires":[["dec6caa7.597b58"]]},{"id":"dd07fc0b.944d8","type":"comment","z":"f11a4d64.917db","name":"Hourly Chime Sound","info":"","x":110,"y":60,"wires":[]},{"id":"2373bee.295db42","type":"simpletime","z":"f11a4d64.917db","name":"","x":1410,"y":140,"wires":[["d3ecb019.e4441"]]},{"id":"d3ecb019.e4441","type":"change","z":"f11a4d64.917db","name":"payload","rules":[{"t":"set","p":"payload","pt":"msg","to":"myhourpm & mypm","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":1580,"y":140,"wires":[["f8e02c52.7ebec"]]},{"id":"f8e02c52.7ebec","type":"sonospollytts","z":"f11a4d64.917db","name":"","voice":"0","ssml":false,"sonosipaddress":"192.168.1.64","sonosvolume":"35","sonoshailing":"Hailing_bigben.mp3","config":"","property":"payload","propertyType":{},"rules":[],"x":1760,"y":140,"wires":[["67c9fc2d.9aba54"]]},{"id":"edf3278e.1169c8","type":"sonos-universal","z":"f11a4d64.917db","confignode":"6bcd8b37.118004","compatibilityMode":false,"command":"group.play.snap","state":"","stateType":"str","name":"Kitchen","x":2780,"y":140,"wires":[["f5305fc0.518cf"]]},{"id":"f5305fc0.518cf","type":"debug","z":"f11a4d64.917db","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":2930,"y":140,"wires":[]},{"id":"ac200b6a.1adee8","type":"change","z":"f11a4d64.917db","name":"store in flow, stop","rules":[{"t":"set","p":"recentsnapshot","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":1110,"y":140,"wires":[["7a91075f.a1bc18"]]},{"id":"56831a1f.d04104","type":"change","z":"f11a4d64.917db","name":"play snapshot","rules":[{"t":"set","p":"snap","pt":"msg","to":"recentsnapshot","tot":"flow"}],"action":"","property":"","from":"","to":"","reg":false,"x":2600,"y":140,"wires":[["edf3278e.1169c8"]]},{"id":"aa7b1ea2.066a","type":"sonos-manage-mysonos","z":"f11a4d64.917db","confignode":"6bcd8b37.118004","name":"Kitchen","x":2420,"y":140,"wires":[["56831a1f.d04104"]]},{"id":"2721b3b8.8c70fc","type":"change","z":"f11a4d64.917db","name":"restoreQ","rules":[{"t":"set","p":"topic","pt":"msg","to":"queueBackup","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":2260,"y":140,"wires":[["aa7b1ea2.066a"]]},{"id":"dec6caa7.597b58","type":"sonos-universal","z":"f11a4d64.917db","confignode":"6bcd8b37.118004","compatibilityMode":false,"command":"household.remove.sonosplaylist","state":"queueBackup","stateType":"str","name":"RemoveSonosPlaylist","x":300,"y":140,"wires":[["fc3f1577.48a178"]]},{"id":"bd981e5.712ede","type":"sonos-universal","z":"f11a4d64.917db","confignode":"6bcd8b37.118004","compatibilityMode":false,"command":"group.create.snap","state":"","stateType":"str","name":"createSnap","x":910,"y":140,"wires":[["ac200b6a.1adee8"]]},{"id":"7a91075f.a1bc18","type":"sonos-universal","z":"f11a4d64.917db","confignode":"6bcd8b37.118004","compatibilityMode":false,"command":"group.stop","state":"","stateType":"str","name":"Stop","x":1270,"y":140,"wires":[["2373bee.295db42"]]},{"id":"67c9fc2d.9aba54","type":"switch","z":"f11a4d64.917db","name":"played","property":"completed","propertyType":"msg","rules":[{"t":"true"}],"checkall":"true","repair":false,"outputs":1,"x":1930,"y":140,"wires":[["cd22b362.cd5ff"]]},{"id":"9d88afb3.b66f","type":"change","z":"f11a4d64.917db","name":"snapVolume","rules":[{"t":"set","p":"snapVolumes","pt":"msg","to":"true","tot":"bool"},{"t":"set","p":"snapMutestates","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":730,"y":140,"wires":[["bd981e5.712ede"]]},{"id":"cd22b362.cd5ff","type":"sonos-universal","z":"f11a4d64.917db","confignode":"6bcd8b37.118004","compatibilityMode":false,"command":"group.clear.queue","state":"","stateType":"str","name":"clearQueue","x":2090,"y":140,"wires":[["2721b3b8.8c70fc"]]},{"id":"fc3f1577.48a178","type":"sonos-universal","z":"f11a4d64.917db","confignode":"8f44d2a.41b103","compatibilityMode":false,"command":"group.save.queue","state":"queueBackup","stateType":"str","name":"","x":530,"y":140,"wires":[["9d88afb3.b66f"]]},{"id":"6bcd8b37.118004","type":"sonos-config","z":"","name":"SonosKitchen","serialnum":"B8-E9-37-B8-23-B6:E","ipaddress":"192.168.1.64"},{"id":"8f44d2a.41b103","type":"sonos-config","z":"","name":"SonosLiving","serialnum":"00-0E-58-BF-B8-4E:E","ipaddress":"192.168.1.14"}]`

**Comment by mfw2010** [comment]
Hi Supergiovane

I seem to have had no issues overnight and the node seems to work absolutely fine, it was probably an issue with my Sonos device/network. Sorry for the bother and thanks for the great support!

**Comment by Supergiovane** [comment]
Good, thank you and thank you for using one of my node!!

**Comment by dxdc** [comment]
@Supergiovane I had a very similar issue but after restarting nodered it seems to be working perfectly! Maybe something from the initial setup?

Also, I had a problem with finding the config node, but after importing your sample flow it worked perfectly. Very cool plugin!
