### ISSUE TITLE
SSML Availability Question

### ISSUE THREAD

**Issue by 0bimaster** [Supergiovane/node-red-contrib-sonospollytts#44]
Hi
In #41 you mentioned that SSML is (not yet) supported. However, the node offers an "Enable SSML" option which indicates the opposite. Is SSML now supported or not and if yes, how do I have to format the payload in order to get it working?

With the "Enable SSML" option enabled, if i omit any SSML tags in the payload (e.g. `This is a test`) I receive an error "Invalid SSML request":
>"SonosPollyTTS: notifyError - msg: /config/node-red//sonospollyttsstorage/ttsfiles/This is a test_Joanna_ssml.mp3 error: Invalid SSML request"

If I enter the SSML tags in the payload (e.g. `<speak>This is a test</speak>`) i receive the same error as in #41 :
> "SonosPollyTTS: notifyError - msg: /config/node-red//sonospollyttsstorage/ttsfiles/_less_speak_greater_This is a test_less_/speak_greater__Joanna_ssml.mp3 error: ENOENT: no such file or directory, open '/config/node-red//sonospollyttsstorage/ttsfiles/_less_speak_greater_This is a test_less_/speak_greater__Joanna_ssml.mp3'"

Thanks

**Comment by Supergiovane** [comment]
Hello 0bi
SSML support is under developing. Unfortunately, coronavirus has slowed down everything and i’ve other two nodes to mantain. 
I’ll continue working on it during this week, because finally i’m on holidays and i have some time to spend!

**Comment by Supergiovane** [comment]
Hello
You need to use a correct SSML syntax.
Please try this:

msg.payload = "<speak><p>Ciao</p><p>Introduction</p><p>Hallo</p><p>Welcome to <break time='2s'/>the jungle</p></speak>";
return msg;

and let me know.
The Amazon Polly service use a very little set of SSML syntax. See here https://docs.aws.amazon.com/polly/latest/dg/supportedtags.html

**Comment by 0bimaster** [comment]
Unfortunately I get the same error:

`"SonosPollyTTS: notifyError - msg: /config/node-red//sonospollyttsstorage/ttsfiles/_less_speak_greater__less_p_greater_Ciao_less_/p_greater__less_p_greater_Introduction_less_/p_greater__less_p_greater_Hallo_less_/p_greater__less_p_greater_Welcome to _less_break time='2s'/_greater_the_{ words: [Array], sigBytes: 16 }_Joanna_ssml.mp3 error: ENOENT: no such file or directory, open '/config/node-red//sonospollyttsstorage/ttsfiles/_less_speak_greater__less_p_greater_Ciao_less_/p_greater__less_p_greater_Introduction_less_/p_greater__less_p_greater_Hallo_less_/p_greater__less_p_greater_Welcome to _less_break time='2s'/_greater_the_{ words: [Array], sigBytes: 16 }_Joanna_ssml.mp3'"`

<img width="1152" alt="Screenshot 2020-07-08 at 22 09 29" src="https://user-images.githubusercontent.com/55250480/86965528-030a7d00-c168-11ea-9985-d3a344535bce.png">
<img width="1370" alt="Screenshot 2020-07-08 at 22 08 21" src="https://user-images.githubusercontent.com/55250480/86965547-09005e00-c168-11ea-83f1-98a75c924ccd.png">

**Comment by Supergiovane** [comment]
Ok
Let me try with the voice Johanna

**Comment by Supergiovane** [comment]
Hello
are you able to unzip and paste this file into **.node-red/node_modules/node-red-contrib-sonospollytts/sonospollytts**  folder and retry?
[sonospollytts.js.zip](https://github.com/Supergiovane/node-red-contrib-sonospollytts/files/4895237/sonospollytts.js.zip)

**Comment by 0bimaster** [comment]
Hi

With the updated sonospollytts.js it's working!

Thx

**Comment by Supergiovane** [comment]
Good. It was a glitch with file naming.
An update version will be out soon, with some more fixing.
