### ISSUE TITLE
Source Switch on Flow deploy

### ISSUE THREAD

**Issue by 0bimaster** [Supergiovane/node-red-contrib-sonospollytts#45]
Hi Supergiovane,

When deploying (either all flows or any flow that contains your sonospollytts node) or restarting, it seems that the node causes the Sonos speakers to stop playback.

E.g. when listening to music while editing flows in Node Red and then deploying the changes, the playback pauses/stops. May it be possible stop this behaviour when the node connects?

thx
0bi

**Comment by Supergiovane** [comment]
Hello 0bi
Yes i know and not, sorry. At start and stop, the node queries the sonos controller to instantiate and release some resources. 
The effort to change this behaviour is too much for the final result. I suggest you to put in a fake sonos Ip during your programming, so the node will not interfere with sonos.
