### ISSUE TITLE
Support for Identifying Specific Speakers

### ISSUE THREAD

**Issue by doublej0** [Supergiovane/node-red-contrib-sonospollytts#46]
Enhancement Request
Currently, there is a main speaker and you can include additional speakers. Could you add the ability to input a specific speaker?

This is my scenario. I have 5 speakers: Bedroom, Kitchen, Living Room, Bathroom, Foyer. I would like to send a good night/morning message to the bedroom speaker, but only the bedroom speaker. However, my Living Room is my "main" speaker. There are other use cases, such as walking in the door and only playing in the foyer. Or walking into the bathroom after waking up and a reminder to take my vitamin.

I could possibly create five sub flows to isolate the speakers using Sonos controller node to mute the speakers I don't want it playing on, but what if I'm playing music in the bathroom only and my girlfriend walks in the front door and I want the foyer speaker to greet her. Now my music is muted.

**Comment by Supergiovane** [comment]
Hello
You could create another sonospollytts node and link it only to one speaker. 
Please give it a try.

**Comment by doublej0** [comment]
* facepalm *
You're right. it works perfectly. I was thinking I could only have one controller node.
