### ISSUE TITLE
Cant upload files

### ISSUE THREAD

**Issue by zimbo86** [Supergiovane/node-red-contrib-sonospollytts#47]
Having issues uploading files to "Own File" or custom hailings.
When I select a file to upload just nothing happens.
Where are these files located in file system?

**Comment by Supergiovane** [comment]
Hello Zimbo
Do your un Node Red behind something, for example home assistant, homematic or something?
I think uou’ve issues with user permission to wrote to the filesystem.

**Comment by zimbo86** [comment]
Hi Supergiovane,
i´m running node red v1.1.2 in a docker container.
Of course it could be a permisstion issue on FS, where are the files uploaded to?

**Comment by Supergiovane** [comment]
.node-red/sonospollyttsstorage

**Comment by Supergiovane** [comment]
Hi Zimbo,
have you solved the issue?

**Comment by zimbo86** [comment]
Hi, 
no - not really. 
What I can see is that I have generally access to /sonospollyttsstorage/ because the cache mp3s are successfully stored in /sonospollyttsstorage/ttsfiles/

**Comment by Supergiovane** [comment]
The file must have the .mp3 extension.
I've tried and all went fine. Even under Docker. 
Please try to unzip and upload the file attached.

[denybeep4.mp3.zip](https://github.com/Supergiovane/node-red-contrib-sonospollytts/files/5035218/denybeep4.mp3.zip)

**Comment by zimbo86** [comment]
Thanks for testing, thats pretty strange.
It also does not work with the file you provided:
[https://gifyu.com/image/WXpl](url)

**Comment by Supergiovane** [comment]
A stupid question: do you have rebooted the machine prior to upload a file?

**Comment by Supergiovane** [comment]
Hello
Have you solved the issue?

**Comment by zimbo86** [comment]
nope - i didnt. 
Tried several reboots, uninstall, reinstall.
Its weird.

Additionally I cant get another Hailing to play than the 3 preinstalled. 
Also when i replace the hailing.mp3 with a custom one

**Comment by Supergiovane** [comment]
I wish to try to reproduce the issue. Can you tell me, please:
1) Where are you running docker? Qnap, Nuc PC, or what?
2) From what client are you opening the web interface? Chrome, Safari, etc.. and on witch operating system.
3) What language are you using in your browser? English, Deutsch....
4) can you issue a "node -v" command in a terminal window and tell me the node version?
Thanks.
