### ISSUE TITLE
Volume of players added as "Additional players" gets not set to specified one

### ISSUE THREAD

**Issue by JorinL** [Supergiovane/node-red-contrib-sonospollytts#48]
Hey there :-)

There has been a nice further development here :-) I'm glad to see that.

I noticed that the players under "Additional Player" do not get the volume value that is set under "Sonos Volume" - they therefore play at the volume that was previously used.
That's at least the case with me

![image](https://user-images.githubusercontent.com/33031729/93993286-da6d4900-fd8e-11ea-8288-3a4c4c67a833.png)

Player on 192.168.0.54 is not playing on Volume 30.

**Comment by Supergiovane** [comment]
Hi Jorin
unfortunately, i haven't any additional player in my home to test this issue, because i use only a Connect-AMP with multiroom speakers.
I'll check that. Maybe i send you a modified js file to test.
Stay tuned.

**Comment by Supergiovane** [comment]
Hi Jorin
Found the issue.
The group volume is set after the play has been started, so the volume doesn't change until next play.
I'm working on a fix.

**Comment by Supergiovane** [comment]
Hi Jorin
Are you able to unzip and replace the unzipped file in the .node-red/nodes/node-red-contrib-sonospollytts/sonospollytts folder, restart node-red try again and let me know?
[sonospollytts.js.zip](https://github.com/Supergiovane/node-red-contrib-sonospollytts/files/5269219/sonospollytts.js.zip)

**Comment by JorinL** [comment]
Yes give me some time - I'll test it :-)

**Comment by JorinL** [comment]
So I tested.

I is not really working. My Sets get muted and play or if play and are muted after.... 
Something seems to be wrong ;-) 

Tested with volume 10.

**Comment by Supergiovane** [comment]
Mmmmmm...
I saw that auto discovery doesn’t work for you. In fact, you see all IP addresses instead of the device names. Are you using node-red behind something? Maybe redmatic or behind a natted docker?

**Comment by JorinL** [comment]
I have running a rancher kubernetes cluster inside that it's all running.

**Comment by Supergiovane** [comment]
I suspect that some api calls, wont pass through the natting. I’ll try tomorrow another approach, just for you. Good night.

**Comment by JorinL** [comment]
Would be nice :-) 
Good night!

**Comment by Supergiovane** [comment]
Hi Jorin.
Can you try this file, please? Unzip and place as before.
[sonospollytts.js.zip](https://github.com/Supergiovane/node-red-contrib-sonospollytts/files/5273964/sonospollytts.js.zip)

**Comment by JorinL** [comment]
Works like charm! :-)
Thank you!!

Different question: When deploying the flow sonospollytts stops all playback - is that needed? Should I open another issue for that? It is.... a bit... annoying ;-)

**Comment by Supergiovane** [comment]
Hi Jorin
Good. I'll publish an official update in the next hours.
And... yes, if you deploy, it stops. That's a normal behaviour because whenever you deploy a node, node-red re-initializes the startup sequence, thus loosing the connection with the sonos. Sorry, i cannot change this behaviour.

**Comment by JorinL** [comment]
Thank you :-)
