### ISSUE TITLE
Problem with Installation 

### ISSUE THREAD

**Issue by Stieger81** [Supergiovane/node-red-contrib-sonospollytts#49]
I Cant install the Node. There is alway an Error. Can you please help me. I Don't know where I can't change something for installation: 

See also here: https://homematic-forum.de/forum/viewtopic.php?f=77&t=61214&p=607039#p607039
<img width="462" alt="Bildschirmfoto 2020-09-26 um 13 45 34" src="https://user-images.githubusercontent.com/71928627/94357723-93879800-009b-11eb-9514-a480303795ef.png">
<img width="620" alt="Bildschirmfoto 2020-09-26 um 13 45 44" src="https://user-images.githubusercontent.com/71928627/94357725-94202e80-009b-11eb-93c4-c83c1f33c4ad.png">
<img width="613" alt="Bildschirmfoto 2020-09-26 um 13 45 48" src="https://user-images.githubusercontent.com/71928627/94357726-94202e80-009b-11eb-85f4-a4ddbe1f8345.png">

**Comment by Supergiovane** [comment]
Hi Stieger.
You don't have permissions to deploy. Check user permissions. I don't know how homematic work, so i cannot help here, but Sonospollytts creates some folders into the .node-red folder, so you need to give the node-red user, the rights to access the filesystem.
