### ISSUE TITLE
can not upload file

### ISSUE THREAD

**Issue by koburg** [Supergiovane/node-red-contrib-sonospollytts#50]
im not able to upload mp3 file directly with the upload option it says 

"error not found" 

have tried from win 10 and macOS webbrowsers 

safari and chrome

**Comment by Supergiovane** [comment]
Hi
you may have issues with write permissions to filesystem. Are you running nodered alone or behind something, like homeassistant?

**Comment by koburg** [comment]
Yeah it is a phoscon conbee image I have installed iobroker/nodered together with.

Den 17. okt. 2020 kl. 13.37 skrev Supergiovane <notifications@github.com<mailto:notifications@github.com>>:



Hi
you may have issues with write permissions to filesystem. Are you running nodered alone or behind something, like homeassistant?

**Comment by Supergiovane** [comment]
So please check the user permissions to write to the filesystem and you’re done!

**Comment by koburg** [comment]
i have now made the file chmod to 777 and folders no luck. 

I can upload hailing tunes no problem but not ownfile do it use another folder ?

and the hailing tunes upload was working before chmod.

**Comment by Supergiovane** [comment]
The folder for ownfiles is 
sonospollyttsstorage/ttspermanentfiles
I don’t know if simply giving 777 will work. 
Have you tried to upload the same working haiking file, to the ownfile node?
Please upgrade sonospollytts to the latest version as well.

**Comment by Supergiovane** [comment]
Tomorrow i’ll take a look deeper and i’ll do sone tests for you!

**Comment by Supergiovane** [comment]
Hi koburg,
Are you able to unzip these files into your **.node.red/node_modules/node-red-contrib-sonospollytts/sonospollytts** folder and restart node-red?

[Archivio.zip](https://github.com/Supergiovane/node-red-contrib-sonospollytts/files/5450097/Archivio.zip)

If not, please wait. I'll release a new version today, that try to fix your issue.
Let me know.

**Comment by koburg** [comment]
I did just installed your update and did not try upload to the folder yet. 

because now I can not restart my nodered. 
don't now why at the moment..

**Comment by koburg** [comment]
I found the reason why the node-red went down it was after upgrading and when dragging the "own fie"l and "tts Sonos" nodes plus attach the two nodes then the server crashed after first deploy. I have not tried the zip file only the upgrade in the nod-red palette.

**Comment by Supergiovane** [comment]
What version of nodered and node.js are you running?

**Comment by Supergiovane** [comment]
PS: Please try to updgrade sonospollytts to V. 1.1.34

**Comment by koburg** [comment]
thank you it do not crash anymore but now the polly key it says it won't load and I have done all the right deployings. but it works with the old settings voice but I can not change the voice now. and throws error. 

<img width="505" alt="588663F7-429C-46D9-8318-32EB07D18C5D" src="https://user-images.githubusercontent.com/3473374/97734345-561e8c00-1ad9-11eb-97bb-1066c344b97d.png">

**Comment by koburg** [comment]
sorry forgot to restart nodered server ok now.
