### ISSUE TITLE
Sonos players can't access to <ip address>:1980

### ISSUE THREAD

**Issue by Gixy31** [Supergiovane/node-red-contrib-sonospollytts#51]
Hi,
node-red is installed in a docker container on a RaspberryPi 4 running RaspberryPi OS. I installed sonospollytts node, without any problem. Then I configured one node, and everything seem to go well, the node says that Sonos is connected, and I can inject a string message, which is said to be played (after conversion in .mp3 by Polly) as seen below the node. But on the Sonos side, I have this type of message:

impossible to read tts.mp3?f=/data/sonospollyttsstorage/hailingpermanentfiles/Hailin_Hailing.mp3 impossible to connect to (IP address):1980

The files exist in the data directory which is mapped outside the container.

Another point is that the discovery doesn't work, but I've put the IP addresses of the Sonos players in the node parameters.
What did I missed? Thank for your support!
Denis

**Comment by Supergiovane** [comment]
Hi
Dockerized versions of nodered are everytime a trouble.
You need to forward porta 1980 (for sonos to contacting nodered) and 1400 (for sonos discovery protocol). 
You should maybe allow mdns through docker, but first try to simply forward the ports.

**Comment by Gixy31** [comment]
Thx for the super-fast answer!
Indeed, I was looking at the port forwarding inside the docker-compose.yml file. I'll try that this evening and let you informed. Thanks again :-)

**Comment by Gixy31** [comment]
I'm back. Well, redirecting port 1980 in the docker-compose config file solved the problem! Sadly, the redirection of port 1400 did not solve the discovery issue.

**Comment by Gixy31** [comment]
Tried to forward also port 3400, still discovery error.

**Comment by Supergiovane** [comment]
Try to run docker as bridged instead of natted, giving it a fixed ip. 
Sonos uses mdns to discover devices. Nat on docker is bad on that.
