### ISSUE TITLE
Restart of flow causes stop of playing music

### ISSUE THREAD

**Issue by PatrickM2201** [Supergiovane/node-red-contrib-sonospollytts#52]
Hello, 
I have installed the latest Version of sonospollytts in Redmatic which runs on a Raspi 4B. 
Since some weeks, I recognized that a restart of Redmatic or a restart of flows causes a stop of currently playing music via Sonos. I am not sure, if this behaviour was there since the "beginning" or came up recently, but some weeks ago I recognized it the first time.
After several try and error attempts I figured out, that once I disable all nodes of sonospollytts, the music does not stop anymore.
It seems, that the music is stopping while "Shutdown" is shown in the node status. This behaviour is also there if nothing is connected to the input of the node, just the restart is triggering the stop.

Is there something I am doing wrong? 
Thank you for your great developments, also boolean-logic-ultimate I am using quite often :-)
Patrick

**Comment by Supergiovane** [comment]
Hi Patrick
This is an intended behaviour. The node checks wheter it can connect to sonos and tracks the play state. This is for reliability pourposes. Restarting nodered is a thing that occurs rarely in a working environment. Please keep the node disabled until you’re done with all your nodered changes, to avoid stopping the music.

**Comment by Supergiovane** [comment]
Hi Patrick
a little follow up. 
I'll take a look if i can change this thing a little bit...
I'll let you know...

**Comment by Supergiovane** [comment]
Hi Patrick,
V. 1.1.36 is out with the fix for your request.
Thank you for using my nodes!

**Comment by PatrickM2201** [comment]
Wow, really great! Thank you very much!
