### ISSUE TITLE
Does this plugin also pause/resume any media that is playing?

### ISSUE THREAD

**Issue by gvdhoven** [Supergiovane/node-red-contrib-sonospollytts#53]
Question: Does this plugin also pause/resume any media that is playing?

**Comment by Supergiovane** [comment]
Hi
It stops the play, but it doesn’t resume after speech. You need to use another sonos node and link the output of sonospollytts to a function that resumes the current queue.

**Comment by gvdhoven** [comment]
ah great, so it _is_ capable of interrupting a playing stream with the announcement, i just have to use another node to restart the playing?

**Comment by Supergiovane** [comment]
Yes, exactly.
Please beer in mind, that all Sonos API that we developers use, are unofficial and undocumented so we must stitch with the bare minimum ones.

**Comment by Supergiovane** [comment]
Duplicate of #54
