### ISSUE TITLE
Could the notification API be used

### ISSUE THREAD

**Issue by timroes** [Supergiovane/node-red-contrib-sonospollytts#54]
It seems whenever this plugin is used it actually queues the sound to speak into the playlist and thus "destroys" it (aka you can actually pause and resume the TTS).

It seems that other sonos plugins have some kind of [notification API](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/A.1-Universal-Node#groupplaynotification) that will just temporarily play a sound without breaking the playlist.

Would it be possible to use something like this for this addon too?

**Comment by Supergiovane** [comment]
Hello to you too, Tim.
Will take a look, but it involves some work, so this will not be an instant change.

**Comment by Vinisz** [comment]
+1

**Comment by Supergiovane** [comment]
Hi all,
resume queue functionality is under development. A new release will be out today.

**Comment by Supergiovane** [comment]
V. 1.1.37 is out with queue resuming.
