### ISSUE TITLE
SonosPollyTTS: Error joining device Error: getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by jayheavner** [Supergiovane/node-red-contrib-sonospollytts#55]
I am running node-red on a proxmox server. That server has an IP of 192.168.1.151. My node-red instance has an IP of 192.168.1.48. The mp3 file is being written to ~/.node-red/sonospollyttsstorage/ttsfiles as expected. The music on my Sonos player stops and the mp3 is played but it's throwing an error both in the debug and in the logs. Not a big deal but it would be nice to get rid of it.

```
30 Nov 20:10:20 - [warn] SonosPollyTTS: Error joining device Error: getaddrinfo EAI_AGAIN null
```

**Comment by Supergiovane** [comment]
Please open and forward the port 1400 as well, for device auto discovery. Passthrough the mdns protocol as well.
