### ISSUE TITLE
NodeRed in HASS.io

### ISSUE THREAD

**Issue by awor** [Supergiovane/node-red-contrib-sonospollytts#56]
Hi,
I am running NodeRed with HomeAssistant in Hass.io. I am getting err currstate: Error: connect ECONNREFUSED 127.0.0.1:1400. I suppose that this is a networking issue related to the Hass.io environment. 
Do you have any info on how your component can be used in Hass.io?
Thanks

**Comment by Supergiovane** [comment]
Hi
You need to open and forward port 1400, for sonos discovery.
