### ISSUE TITLE
resume music queue should also include the current playing radio station

### ISSUE THREAD

**Issue by mschoenel** [Supergiovane/node-red-contrib-sonospollytts#57]
It would be very helpfull if the current playing radio station will be also stored in the music queue.
Do you think it is possoble?

**Comment by Supergiovane** [comment]
Hi
i don't know if it's even possible to store a radio station in a queue. IT's a matter of Sonos capabilities.
I can see if a radio station can be played again after a stop.
I'll take a look.

**Comment by Supergiovane** [comment]
PS: Please give me the radio url of your station.

**Comment by Supergiovane** [comment]
V.2.0.1 is out with radio station resume support.
Please, give a star to my node, i'll appreciate that.
