### ISSUE TITLE
Extra language added to payload

### ISSUE THREAD

**Issue by scmilius** [Supergiovane/node-red-contrib-sonospollytts#59]
Hi.  Really great node you've created.  After recently updating to v. 2.0.1, spoken payloads now include the spoken word "Zero" before the actual payload is spoken.  I have checked the payload and the "zero" is definitely not part of the payload.  Seems like it might perhaps be related to internal queuing that the node might use.  Thanks.

**Comment by Supergiovane** [comment]
Hello,
Can you post here, please, the payload you're sending to sononspollytts or, better, your flow?
I cannor reproduce your issue.
Thanks.

**Comment by Supergiovane** [comment]
Hello,
i maybe understood what the problem is related to. Please set again the hailing in the config node.
You installed sonospollytts very long time ago, so you have a very old setting.

**Comment by Supergiovane** [comment]
V. 2.0.2 is out with workaround for your issue, but please re-select the hailing in the config node to fix it forever.

**Comment by Supergiovane** [comment]
Thank you Scott for your donation. I really appreciate that!
