### ISSUE TITLE
Multiple Nodes Wrong Speaker Selection

### ISSUE THREAD

**Issue by pums12** [Supergiovane/node-red-contrib-sonospollytts#8]
Hi,

I have a  SonosPolly node setup for each of my three speakers.  The problem I am having is that it is playing through the Sonos IP of the last node that I add to the flow regardless of which path the message is taking.

Even if the last node I add is not attached to anything, the Sonos IP from that node is used for all speech. 

Any ideas what might be causing the problem?

**Comment by Supergiovane** [comment]
Hello
Do you need 3 different speakers, working independently?
If yes, i need to work on the plugin, because for each speaker, i need to create an instance of the web server , each communicating with a speaker. 
 If you wish to play the same speech on all, you may simoke group your speakers through Sonos app.

**Comment by pums12** [comment]
I have various announcements (doors opened etc) that are played out all the speakers at the same time but other things such as morning weather reports are just played from single speakers at different times.

**Comment by Supergiovane** [comment]
Ok, please leave me some time to look into. Have a goor weekend.

**Comment by pums12** [comment]
Thanks, there's no rush though. I have just set it all up using the Home Assistant nodes and it seems to be working well.

![image](https://user-images.githubusercontent.com/6554837/55674049-36949280-58a7-11e9-90a9-7c7fa6aec54d.png)

**Comment by Supergiovane** [comment]
Good job, well done.

**Comment by Supergiovane** [comment]
Hello pums12,
the upcoming 1.0.8 should fix the multi node issue.
